/* AnthroMeta — anthrometa.com — Shared JS */

const T = {
  ko:{
    nav_home:'홈', nav_about:'회사소개', nav_services:'서비스', nav_clients:'거래처', nav_blog:'블로그', nav_qa:'Q&A', nav_contact:'문의하기', nav_quote:'견적문의',
    /* About */
    ab_tag:'ABOUT US', ab_title:'앤트로메타 소개', ab_sub:'기술로 비즈니스의 내일을 설계하는 IT 솔루션 전문기업',
    ab_mv_tag:'MISSION & VISION', ab_mv_title:'미션과 비전',
    ab_mission_h:'🎯 미션', ab_mission_p:'중소·중견기업이 최신 IT 기술을 통해 디지털 혁신을 이루고, 더 나은 경쟁력을 갖출 수 있도록 실질적이고 지속 가능한 솔루션을 제공합니다.',
    ab_vision_h:'🔭 비전', ab_vision_p:'기업의 디지털 전환 여정에서 가장 신뢰받는 IT 파트너로 자리매김하며, AI와 데이터 기반 솔루션으로 산업 전반의 스마트 혁신을 이끌어 나갑니다.',
    ab_info_tag:'COMPANY', ab_info_title:'회사 정보',
    ab_intro:'앤트로메타는 2022년 경기도 파주시에서 설립된 IT 솔루션 전문기업입니다. ERP 구축부터 홈페이지 제작, ISMS 컨설팅, AI 기반 솔루션, 로컬 LLM 구축까지 기업 디지털 혁신의 전 단계를 원스톱으로 지원합니다.',
    ab_intro2:'노루홀딩스, 기반테크, 우영테크 등 제조·유통·의료 분야 다양한 기업과의 실전 레퍼런스를 바탕으로, 각 업종에 최적화된 IT 솔루션을 빠르고 정확하게 납품합니다.',
    ab_tl_tag:'HISTORY', ab_tl_title:'연혁', ab_tl_sub:'앤트로메타의 성장 여정',
    tl1_t:'앤트로메타 설립', tl1_d:'경기도 파주시에서 IT 솔루션 전문기업으로 창업. ERP 및 홈페이지 제작 사업 개시.',
    tl2_t:'노루홀딩스 홈페이지 구축', tl2_d:'대기업 계열 지주사 공식 홈페이지 기획·설계·구축. 첫 대형 레퍼런스 확보.',
    tl3_t:'제조업 레퍼런스 확장', tl3_d:'기반테크(스마트팜), 우영테크(다국어 홈피) 등 제조·IT 분야 레퍼런스 다수 확보.',
    tl4_t:'ISMS 컨설팅 서비스 출시', tl4_d:'정보보안 전문 인력 영입, ISMS·ISMS-P 인증 컨설팅 서비스 공식 런칭.',
    tl5_t:'의료기관 홈페이지 다수 납품', tl5_d:'병원·의원·클리닉 등 의료기관 특화 홈페이지 솔루션 완성. 대한신경과협회 계약 체결.',
    tl6_t:'로컬 LLM AI 솔루션 서비스 론칭', tl6_d:'온프레미스 대형언어모델(LLM) 구축 서비스 개시. 데이터 보안이 중요한 기업 대상 AI 솔루션 제공.',
    tl7_t:'지속 성장 중', tl7_d:'ERP·AI·LLM 통합 솔루션 확장 및 신규 파트너십 구축. 더 많은 기업의 디지털 혁신을 지원합니다.',
    ab_val_tag:'CORE VALUES', ab_val_title:'핵심 가치', ab_val_sub:'앤트로메타가 일하는 방식',
    val1_t:'신속성', val1_p:'빠른 납기와 즉각적인 커뮤니케이션으로 비즈니스 기회를 놓치지 않도록 지원합니다.',
    val2_t:'전문성', val2_p:'각 분야 전문 인력이 기획부터 구축, 운영까지 최고 수준의 품질을 보장합니다.',
    val3_t:'신뢰성', val3_p:'100% 프로젝트 완수 원칙과 투명한 소통으로 고객과 장기적 파트너십을 유지합니다.',
    val4_t:'혁신성', val4_p:'AI·LLM 등 최신 기술을 빠르게 비즈니스에 적용하여 경쟁 우위를 창출합니다.',
    /* Blog */
    blog_tag:'INSIGHT & BLOG', blog_title:'IT 인사이트', blog_sub:'AI · ERP · 웹개발 · 보안 분야의 최신 트렌드와 실무 노하우',
    cat_all:'전체', cat_ai:'AI · LLM', cat_web:'웹개발', cat_erp:'ERP', cat_sec:'보안',
    /* Quote */
    qt_tag:'QUOTE REQUEST', qt_title:'견적 문의', qt_sub:'프로젝트 정보를 입력해 주시면 24시간 이내 맞춤 견적을 제공합니다',
    qt_proc_t:'🗓️ 견적 프로세스', qt_s1:'양식 작성 & 제출', qt_s2:'24시간 이내 담당자 연락', qt_s3:'요구사항 상세 미팅 (온/오프)', qt_s4:'맞춤 견적서 발송', qt_s5:'계약 & 프로젝트 착수',
    qt_tip_t:'💡 이런 분께 추천', qt_tip_p:'홈페이지·ERP·AI 도입이 필요하지만 어디서 시작해야 할지 모르는 분, 예산을 먼저 파악하고 싶은 분 모두 환영합니다.',
    qt_contact_t:'📧 빠른 문의', qt_contact_p:'양식 대신 이메일로 바로 문의하셔도 됩니다.',
    qt_f_svc:'서비스 선택 (복수 선택 가능)', qt_f_basic:'기본 정보', qt_f_project:'프로젝트 정보',
    qt_f_company:'회사명', qt_f_name:'담당자명', qt_f_email:'이메일', qt_f_phone:'연락처 (선택)',
    qt_f_budget:'예산 범위', qt_bud0:'선택하세요', qt_bud1:'500만원 이하', qt_bud2:'500 ~ 1,000만원', qt_bud3:'1,000 ~ 3,000만원', qt_bud4:'3,000만원 이상', qt_bud5:'미정 / 협의',
    qt_f_schedule:'희망 완료 시기', qt_sch0:'선택하세요', qt_sch1:'1개월 이내', qt_sch2:'1 ~ 3개월', qt_sch3:'3 ~ 6개월', qt_sch4:'6개월 이상', qt_sch5:'미정 / 협의',
    qt_f_desc:'프로젝트 내용', qt_agree:'개인정보 수집 및 이용에 동의합니다. 수집된 정보는 견적 제공 목적으로만 사용되며, 제3자에게 제공되지 않습니다.',
    qt_submit:'견적 요청 보내기', qt_ok_t:'견적 요청이 접수됐습니다!', qt_ok_p:'24시간 이내에 담당자가 연락드리겠습니다.', qt_ok_btn:'홈으로 돌아가기',
    /* Hero */
    hero_badge:'IT 솔루션 전문기업 · 경기도 파주',
    hero_title:'기술로 비즈니스의<br>내일을 설계합니다',
    hero_sub:'ERP · 홈페이지 · ISMS · AI 솔루션 전문기업',
    hero_cta1:'서비스 보기', hero_cta2:'문의하기', hero_scroll:'SCROLL',
    /* About */
    about_tag:'회사 소개', about_title:'기술로 미래를 여는 기업',
    about_desc:'앤트로메타는 2022년 경기도 파주에서 설립된 IT 솔루션 전문기업입니다. ERP 구축부터 웹사이트 제작, ISMS 컨설팅, AI 솔루션까지 기업 디지털 혁신의 모든 단계를 지원합니다.',
    about_lb1:'설립', about_lv1:'2022년 4월',
    about_lb2:'소재지', about_lv2:'경기도 파주시',
    about_lb3:'업종', about_lv3:'IT 솔루션',
    /* Stats */
    st1l:'설립 연도', st2l:'완료 프로젝트', st3l:'전문 서비스', st4l:'고객 만족',
    /* Services preview */
    svc_prev_tag:'SERVICES', svc_prev_title:'주요 서비스',
    svc_prev_desc:'기업의 디지털 혁신을 위한 맞춤형 솔루션',
    svc_link:'모든 서비스 보기 →',
    s1t:'ERP 솔루션', s1p:'기업 맞춤형 ERP 구축 · 운영',
    s2t:'홈페이지 제작', s2p:'기업·병원·기관 웹사이트',
    s3t:'카탈로그 디자인', s3p:'브랜드 홍보물 기획·제작',
    s4t:'ISMS 컨설팅', s4p:'정보보안 인증 취득 지원',
    s5t:'AI 기반 솔루션', s5p:'업무 자동화 · AI 도입',
    /* Services page detail */
    svc_tag:'SERVICES', svc_title:'주요 사업 영역',
    svc_desc:'기업의 디지털 혁신을 위한 맞춤형 솔루션을 제공합니다',
    s1d:'기업 환경에 최적화된 맞춤형 ERP 시스템을 구축합니다. 업무 프로세스 분석부터 도입, 운영 지원까지 원스톱으로 제공합니다.',
    s1k1:'맞춤형 구축', s1k2:'프로세스 최적화', s1k3:'운영 지원',
    s2d:'기업, 병원, 공공기관을 위한 전문 웹사이트를 구축합니다. 반응형 디자인과 SEO 최적화로 비즈니스 성과를 높입니다.',
    s2k1:'기업/병원/기관', s2k2:'반응형', s2k3:'SEO',
    s3d:'브랜드 아이덴티티를 반영한 기업 홍보물을 기획·제작합니다. 카탈로그, 브로슈어, 리플렛 등 다양한 인쇄물을 제작합니다.',
    s3k1:'브랜딩', s3k2:'인쇄물', s3k3:'브로슈어',
    s4d:'정보보안 관리체계(ISMS) 인증 취득을 위한 전문 컨설팅을 제공합니다. 갭분석부터 인증심사 대응까지 전 과정을 지원합니다.',
    s4k1:'갭분석', s4k2:'인증 지원', s4k3:'보안정책',
    s5d:'업무 자동화 및 AI 기술 도입 컨설팅을 제공합니다. 기업에 최적화된 AI 솔루션으로 생산성과 경쟁력을 향상시킵니다.',
    s5k1:'업무 자동화', s5k2:'AI 컨설팅', s5k3:'생산성 향상',
    /* Clients */
    cl_strip_tag:'CLIENTS', cl_strip_title:'주요 거래처',
    cl_link:'거래처 더보기 →',
    cl_tag:'CLIENTS', cl_title:'주요 거래처',
    cl_desc:'다양한 산업 분야의 기업들과 함께 성장하고 있습니다',
    cl_hosp:'의료/병원 다수', cl_neuro:'대한신경과협회',
    cl_hosp_name:'의료기관 다수',
    cb_svc1:'도료·화학 홈페이지', cb_svc2:'농생명 영상제작', cb_svc3:'스마트팜 카탈+홈피',
    cb_svc4:'다국어 홈피 · ERP', cb_svc5:'카탈로그 · IT MOU', cb_svc6:'홈페이지 제작', cb_svc7:'홈페이지 준비중',
    cl_trust:'앤트로메타는 노루홀딩스, 더기반, 기반테크, 우영테크, 벗앤벗 등 다양한 기업 및 다수의 의료기관 홈페이지를 제작·납품하며 신뢰를 쌓아왔습니다. 규모와 업종을 불문하고 최고의 서비스를 제공합니다.',
    /* Reference cards */
    ref_tag:'REFERENCES', ref_title:'프로젝트 레퍼런스', ref_desc:'앤트로메타가 함께한 대표 프로젝트를 소개합니다',
    rc1_cat:'홈페이지 제작', rc1_t1:'기업 홈페이지', rc1_t2:'반응형 디자인', rc1_t3:'SEO 최적화',
    rc1_sub:'Corporate Website · 대기업 공식 홈페이지',
    rc1_desc:'노루페인트·노루오토코팅 등 다수 계열사를 보유한 종합 지주회사 노루홀딩스의 공식 홈페이지를 기획·설계·구축하였습니다. 대기업의 브랜드 아이덴티티를 온라인에서 강력하게 표현하기 위해 고품격 UI/UX 디자인을 적용하였으며, PC·태블릿·모바일 전 기기 최적화 반응형 구조로 제작하였습니다.',
    rc1_l1:'계열사 통합 브랜딩 페이지 기획 및 구축', rc1_l2:'반응형·모바일 퍼스트 디자인 적용',
    rc1_l3:'IR·뉴스룸·채용 전용 페이지 제작', rc1_l4:'페이지 속도 최적화 및 SEO 세팅',
    rc2_cat:'영상 제작', rc2_t1:'기업 홍보 영상', rc2_t2:'촬영·편집', rc2_t3:'모션 그래픽',
    rc2_sub:'Video Production · 기업 홍보 영상 제작',
    rc2_desc:'㈜ 더기반의 브랜드 가치와 핵심 역량을 효과적으로 전달하는 기업 홍보 영상을 기획부터 최종 납품까지 전 과정을 담당하였습니다.',
    rc2_l1:'기업 홍보 영상 스토리보드 기획', rc2_l2:'전문 장비 활용 현장 촬영 진행',
    rc2_l3:'모션 그래픽·자막·BGM 삽입 편집', rc2_l4:'유튜브·SNS·PPT 다중 포맷 납품',
    rc3_cat:'카탈로그 + 홈페이지', rc3_t1:'제품 카탈로그', rc3_t2:'기업 홈페이지', rc3_t3:'B2B 특화',
    rc3_sub:'Catalog Design + Website · 제조·기술 전문기업',
    rc3_desc:'기술력 중심의 제조·IT 전문기업 ㈜ 기반테크의 제품 카탈로그 제작과 기업 홈페이지 구축을 동시에 진행하였습니다.',
    rc3_l1:'제품 라인업 전체 카탈로그 기획·제작', rc3_l2:'B2B 영업 특화 디자인 및 레이아웃',
    rc3_l3:'기업 홈페이지 설계 및 구축', rc3_l4:'디지털·인쇄 겸용 고해상도 파일 납품',
    rc4_cat:'카탈로그 + 다국어 홈페이지', rc4_t1:'다국어 홈페이지', rc4_t2:'카탈로그 제작', rc4_t3:'ERP 준비중',
    rc4_ongoing:'ERP 도입 진행중',
    rc4_sub:'Multilingual Website + Catalog · ERP Implementation (Upcoming)',
    rc4_desc:'글로벌 시장을 타깃으로 하는 우영테크의 다국어 홈페이지와 해외 바이어용 영문 제품 카탈로그를 제작하였습니다. 현재는 맞춤형 ERP 시스템 도입을 앤트로메타와 함께 준비하고 있습니다.',
    rc4_l1:'한국어·영어·일본어 다국어 홈페이지 구축', rc4_l2:'해외 바이어 대상 영문 제품 카탈로그 제작',
    rc4_l3:'글로벌 SEO 최적화 및 해외 검색 노출 강화', rc4_l4:'맞춤형 ERP 시스템 도입 컨설팅 진행중',
    rc5_cat:'카탈로그 + IT MOU', rc5_t1:'브랜드 카탈로그', rc5_t2:'브로슈어', rc5_t3:'IT 컨설팅 MOU',
    rc5_ongoing:'MOU 파트너',
    rc5_sub:'Catalog Design · IT Consulting MOU · 전략적 IT 파트너십',
    rc5_desc:'㈜ 벗앤벗의 브랜드 정체성을 담은 제품·서비스 카탈로그를 전면 기획·제작하였습니다. 납품 이후 IT 컨설팅 분야 MOU(양해각서)를 체결, 디지털 전환 전반에 걸친 전략적 IT 파트너십을 구축하였습니다.',
    rc5_l1:'브랜드 아이덴티티 반영 카탈로그 전면 기획·제작', rc5_l2:'인쇄용 CMYK + 디지털 RGB 이중 포맷 납품',
    rc5_l3:'IT 컨설팅 분야 MOU 체결 — 전략적 파트너십', rc5_l4:'디지털 전환 로드맵 공동 수립 및 지속 협력',
    rc6_cat:'의료기관 홈페이지', rc6_t1:'병원·의원', rc6_t2:'진료 예약 연동', rc6_t3:'모바일 최적화',
    rc6_name:'의료기관 다수',
    rc6_sub:'Medical Website · 병원·의원·클리닉 홈페이지',
    rc6_desc:'내과, 피부과, 치과, 한의원 등 다양한 진료과목의 의료기관 홈페이지를 다수 제작·납품한 실적을 보유하고 있습니다.',
    rc6_l1:'환자 중심 UX 기반 의료 홈페이지 구축', rc6_l2:'진료과목·의료진·시설 소개 콘텐츠 구성',
    rc6_l3:'온라인 예약 시스템 연동', rc6_l4:'의료법 준수·개인정보보호 설계 기본 탑재',
    rc7_cat:'의료단체 홈페이지', rc7_t1:'의료 전문 단체', rc7_t2:'기관 홈페이지', rc7_t3:'준비중',
    rc7_ongoing:'제작 준비중',
    rc7_name:'대한신경과협회',
    rc7_sub:'Medical Association Website · 전문 의료단체 공식 홈페이지',
    rc7_desc:'대한민국 신경과 전문의를 대표하는 대한신경과협회의 공식 홈페이지 구축을 준비하고 있습니다.',
    rc7_l1:'전국 신경과 전문의 대표 협회 공식 홈페이지 구축', rc7_l2:'회원 관리·학술 정보·학회 일정 통합 플랫폼 설계',
    rc7_l3:'의료 전문가·일반인 대상 이중 UX 구조 설계', rc7_l4:'접근성 + 다국어 지원 적용 예정',
    ind_h:'다양한 산업에 걸친 전문성',
    /* CTA */
    cta_title:'프로젝트를 시작할 준비가 되셨나요?',
    cta_desc:'부담 없이 문의해 주세요. 빠르고 친절하게 답변드립니다.',
    cta_btn:'지금 문의하기',
    /* Q&A */
    qa_tag:'FAQ', qa_title:'자주 묻는 질문', qa_desc:'궁금하신 사항을 확인해보세요',
    q1q:'홈페이지 제작 기간은 얼마나 걸리나요?',
    q1a:'일반적인 기업 홈페이지의 경우 기획·디자인·개발을 포함하여 약 4~8주가 소요됩니다. 프로젝트의 규모와 요구사항에 따라 기간이 달라질 수 있으며, 병원이나 대형 기관의 경우 추가 기간이 필요할 수 있습니다. 초기 상담을 통해 정확한 일정을 안내해 드립니다.',
    q2q:'ERP 구축 비용은 어떻게 되나요?',
    q2a:'ERP 구축 비용은 기업 규모, 필요한 모듈 수, 커스터마이징 범위에 따라 크게 달라집니다. 소규모 기업부터 중견 기업까지 다양한 예산에 맞춘 솔루션을 제안드립니다. 정확한 견적은 요구사항 분석 후 안내해 드리오니, 먼저 문의해 주시기 바랍니다.',
    q3q:'ISMS 인증 준비는 얼마나 걸리나요?',
    q3a:'ISMS 인증 취득까지는 기업의 현황에 따라 통상 6개월~1년 정도 소요됩니다. 갭분석, 보안정책 수립, 보안통제 구현, 내부감사, 심사 준비 등의 단계를 거칩니다. 저희 전문 컨설턴트가 전 과정을 밀착 지원하여 최단 기간 내 인증 취득을 도와드립니다.',
    q4q:'홈페이지 구축 후 유지보수 계약이 가능한가요?',
    q4a:'네, 가능합니다. 홈페이지 구축 완료 후 월정액 유지보수 계약을 체결하실 수 있습니다. 정기적인 콘텐츠 업데이트, 보안 패치, 장애 대응, 기능 개선 등을 포함한 맞춤형 유지보수 플랜을 제공합니다.',
    q5q:'소규모 스타트업도 의뢰할 수 있나요?',
    q5a:'물론입니다. 앤트로메타는 스타트업부터 중견 기업까지 규모에 관계없이 서비스를 제공합니다. 예산과 요구사항에 맞는 최적의 솔루션을 제안하며, 작은 프로젝트도 동일한 품질과 열정으로 진행합니다. 부담 없이 문의해 주세요.',
    /* Contact */
    ct_tag:'CONTACT', ct_title:'문의하기',
    ct_desc:'프로젝트에 대해 이야기해 보세요. 빠르고 친절하게 답변드립니다.',
    ct_sub:'지금 바로 상담을 시작하세요', ct_kbtn:'카카오톡으로 문의하기',
    ct_el:'이메일', ct_pl:'전화', ct_ll:'위치', ct_loc:'경기도 파주시',
    /* Footer */
    /* Why */
    why_tag:'차별화 포인트', why_title:'왜 앤트로메타인가?', why_desc:'고객의 성공이 우리의 목표입니다',
    why1_t:'전문 인력', why1_d:'ERP·웹·ISMS·AI 각 분야 전담 전문가가 처음부터 끝까지 직접 담당합니다.',
    why2_t:'검증된 신뢰', why2_d:'노루홀딩스 등 다수 기업·의료기관과의 납품 실적으로 신뢰를 쌓아왔습니다.',
    why3_t:'신속한 착수', why3_d:'상담 후 빠른 일정 수립, 납기 준수를 최우선으로 합니다.',
    why4_t:'지속적 동반자', why4_d:'납품 후에도 유지보수·업그레이드로 장기 파트너십을 유지합니다.',
    /* Process */
    proc_tag:'PROCESS', proc_title:'프로젝트는 이렇게 진행됩니다',
    proc1_n:'01', proc1_t:'무료 상담', proc1_d:'비즈니스 목표와 요구사항을 정확히 파악하고 프로젝트 방향을 수립합니다.',
    proc2_n:'02', proc2_t:'기획 & 설계', proc2_d:'분석 결과를 바탕으로 최적의 솔루션을 설계하고 견적을 제안합니다.',
    proc3_n:'03', proc3_t:'개발 & 구현', proc3_d:'전담 전문가 팀이 높은 품질 기준으로 개발·구현합니다.',
    proc4_n:'04', proc4_t:'납품 & 사후 지원', proc4_d:'완성도 높은 납품과 지속적인 유지보수·업그레이드를 제공합니다.',
    /* Service features */
    s1b1:'업무 프로세스 분석 및 재설계', s1b2:'모듈별 맞춤 커스터마이징', s1b3:'데이터 마이그레이션 및 연동', s1b4:'직원 교육 및 운영 지원',
    s2b1:'기업·병원·기관 전문 구축', s2b2:'반응형·모바일 최적화 디자인', s2b3:'SEO 최적화 및 성능 튜닝', s2b4:'CMS 연동 및 콘텐츠 관리 시스템',
    s3b1:'브랜드 아이덴티티 완벽 반영', s3b2:'카탈로그·브로슈어·리플렛 제작', s3b3:'디지털·인쇄 겸용 파일 제공', s3b4:'다국어 버전 제작 가능',
    s4b1:'현황 갭분석 및 로드맵 수립', s4b2:'보안 정책·지침서 문서화', s4b3:'임직원 정보보안 교육', s4b4:'인증 심사 대응 및 사후 관리',
    s5b1:'업무 자동화 도구 도입 지원', s5b2:'챗봇·AI 어시스턴트 구축', s5b3:'데이터 분석 및 시각화 시스템', s5b4:'AI 도입 전략 컨설팅',
    /* 로컬 LLM AI 솔루션 */
    s6t:'로컬 LLM AI 솔루션', s6p:'온프레미스 AI · 완전 프라이빗',
    s6d:'기업 내부에 LLM(대규모 언어모델)을 직접 구축·운용하여 데이터가 외부로 유출되지 않는 완전 프라이빗 AI 환경을 제공합니다. 클라우드 의존 없이 사내 서버에서 동작하는 온프레미스 AI로 보안과 생산성을 동시에 확보합니다.',
    s6k1:'온프레미스 AI', s6k2:'데이터 보안', s6k3:'맞춤 파인튜닝',
    s6b1:'사내 서버 기반 LLM 구축 및 최적화', s6b2:'사업 도메인 특화 파인튜닝(Fine-tuning)',
    s6b3:'사내 문서·DB 연동 RAG 시스템 구축', s6b4:'완전 폐쇄망 운용 — 데이터 외부 유출 Zero',
    /* 업데이트된 레퍼런스 설명 */
    rc1_t1:'도료·화학 지주사', rc1_sub:'Corporate Website · 한국 대표 도료기업 공식 홈페이지',
    rc1_desc:'노루페인트·노루오토코팅 등 26개 계열사를 보유한 한국 도료산업 대표 지주회사 노루홀딩스의 공식 홈페이지를 기획·설계·구축하였습니다. 건축용·공업용·자동차용 도료 및 농생명 사업 전반의 브랜드 가치를 온라인에서 효과적으로 전달하기 위해 고품격 UI/UX를 적용하였습니다.',
    rc1_l1:'26개 계열사 통합 그룹 홈페이지 기획·구축', rc1_l2:'도료·농생명 사업부 소개 구조 설계',
    rc2_t1:'농생명 전문기업', rc2_t2:'기업 홍보 영상', rc2_t3:'촬영·편집',
    rc2_sub:'Video Production · 노루홀딩스 계열 농생명 기업 홍보 영상',
    rc2_desc:'노루홀딩스 계열의 농생명 전문기업 ㈜ 더기반의 브랜드 가치와 스마트팜·농업 자재 분야 기술력을 전달하는 기업 홍보 영상을 기획부터 최종 납품까지 전 과정 담당하였습니다.',
    rc2_l1:'농생명·스마트팜 브랜드 홍보 영상 기획',
    rc3_t1:'스마트팜 전문기업', rc3_t2:'제품 카탈로그', rc3_t3:'기업 홈페이지',
    rc3_sub:'Catalog + Website · 스마트팜 자동제어시스템 전문기업',
    rc3_desc:'스마트팜 자동제어시스템·공조시스템 개발 전문기업 ㈜ 기반테크의 제품 카탈로그와 기업 홈페이지를 동시에 제작·납품하였습니다. 차광제·종자 코팅제·친환경 농업소재 등 스마트팜 전 제품 라인업을 B2B 특화 디자인으로 표현하여 영업 경쟁력을 강화하였습니다.',
    rc3_l1:'스마트팜 제품 전 라인업 카탈로그 기획·제작', rc3_l2:'국내외 바이어 대상 B2B 특화 디자인 적용',
    rc3_l3:'기업 홈페이지 설계·구축 (기술력·성장성 강조)',
    /* New FAQs */
    q6q:'프로젝트 계약은 어떻게 진행되나요?',
    q6a:'요구사항 분석 후 견적서와 계약서를 작성합니다. 일반적으로 계약금 50% · 중도금 30% · 잔금 20% 형태이며, 프로젝트 규모에 따라 협의 가능합니다. 계약서에는 산출물, 일정, 납품 기준이 명확히 명시됩니다.',
    q7q:'지방에 있어도 프로젝트 의뢰가 가능한가요?',
    q7a:'물론입니다. 경기도 파주 기반이지만 화상 회의와 원격 협업 툴을 통해 전국 어디서나 동일한 품질의 서비스를 제공합니다. 필요 시 직접 방문 미팅도 협의 가능합니다.',
    q8q:'진행한 프로젝트 포트폴리오를 볼 수 있나요?',
    q8a:'카카오톡 채널 또는 이메일로 문의 주시면 기밀 계약 범위 내에서 관련 포트폴리오와 레퍼런스를 안내해 드립니다. 업종별 납품 사례를 최대한 상세히 공유드리겠습니다.',
    /* Industries */
    ind_title:'서비스 산업군', ind1:'제조업', ind2:'의료·바이오', ind3:'IT·소프트웨어', ind4:'유통·물류', ind5:'공공·기관', ind6:'스타트업',
    /* Contact extras */
    ct_hrs_title:'운영 시간', ct_hrs:'평일 09:00 – 18:00\n(토·일·공휴일 휴무)',
    ct_resp_title:'응답 시간', ct_resp:'문의 접수 후\n24시간 이내 답변',
    ft_co:'앤트로메타', ft_loc:'경기도 파주시', ft_est:'설립 2022년 4월', ft_r:'All rights reserved.'
  },
  en:{
    nav_home:'Home', nav_about:'About', nav_services:'Services', nav_clients:'Clients', nav_blog:'Blog', nav_qa:'Q&A', nav_contact:'Contact', nav_quote:'Get Quote',
    ab_tag:'ABOUT US', ab_title:'About AnthroMeta', ab_sub:'The IT solutions company designing tomorrow\'s business through technology',
    ab_mv_tag:'MISSION & VISION', ab_mv_title:'Mission & Vision',
    ab_mission_h:'🎯 Mission', ab_mission_p:'We provide practical and sustainable IT solutions to help small and mid-sized enterprises achieve digital transformation and build stronger competitiveness.',
    ab_vision_h:'🔭 Vision', ab_vision_p:'We aim to become the most trusted IT partner in every company\'s digital journey, driving smart innovation across industries with AI and data-driven solutions.',
    ab_info_tag:'COMPANY', ab_info_title:'Company Info',
    ab_intro:'AnthroMeta is an IT solutions company founded in Paju, Gyeonggi-do in April 2022. From ERP implementation to website development, ISMS consulting, AI solutions, and local LLM deployment, we support every stage of enterprise digital transformation.',
    ab_intro2:'Backed by real-world references across manufacturing, distribution, and healthcare — including Noru Holdings, Giban Tech, and Woo Young Tech — we deliver IT solutions optimized for each industry, quickly and accurately.',
    ab_tl_tag:'HISTORY', ab_tl_title:'Our History', ab_tl_sub:'The growth journey of AnthroMeta',
    tl1_t:'AnthroMeta Founded', tl1_d:'Established in Paju, Gyeonggi-do as an IT solutions firm. Launched ERP and website development services.',
    tl2_t:'Noru Holdings Website Built', tl2_d:'Planned, designed, and built the official website for a major conglomerate holding company. First large-scale reference secured.',
    tl3_t:'Manufacturing References Expanded', tl3_d:'Secured multiple references in manufacturing/IT sectors including Giban Tech (smart farm) and Woo Young Tech (multilingual site).',
    tl4_t:'ISMS Consulting Service Launched', tl4_d:'Recruited information security specialists and officially launched ISMS/ISMS-P certification consulting service.',
    tl5_t:'Multiple Medical Websites Delivered', tl5_d:'Completed healthcare-specific website solutions for hospitals, clinics, and medical offices. Contract signed with Korean Neurological Association.',
    tl6_t:'Local LLM AI Solution Launched', tl6_d:'Launched on-premises LLM deployment service. AI solutions provided for enterprises where data security is critical.',
    tl7_t:'Continuing to Grow', tl7_d:'Expanding ERP/AI/LLM integrated solutions and building new partnerships. Supporting digital transformation for more enterprises.',
    ab_val_tag:'CORE VALUES', ab_val_title:'Core Values', ab_val_sub:'The AnthroMeta way of working',
    val1_t:'Speed', val1_p:'We support clients with fast delivery and immediate communication so no business opportunity is missed.',
    val2_t:'Expertise', val2_p:'Specialists in each field guarantee the highest quality from planning through implementation and operation.',
    val3_t:'Reliability', val3_p:'Our 100% project completion principle and transparent communication build long-term partnerships with clients.',
    val4_t:'Innovation', val4_p:'We rapidly apply the latest technologies — AI, LLM, and more — to create competitive advantage for our clients.',
    blog_tag:'INSIGHT & BLOG', blog_title:'IT Insights', blog_sub:'Latest trends and practical know-how in AI · ERP · Web development · Security',
    cat_all:'All', cat_ai:'AI · LLM', cat_web:'Web Dev', cat_erp:'ERP', cat_sec:'Security',
    qt_tag:'QUOTE REQUEST', qt_title:'Request a Quote', qt_sub:'Submit your project details and we\'ll provide a custom quote within 24 hours',
    qt_proc_t:'🗓️ Quote Process', qt_s1:'Fill out & submit the form', qt_s2:'Our team contacts you within 24h', qt_s3:'Detailed requirements meeting (online/offline)', qt_s4:'Custom quote sent', qt_s5:'Contract & project kickoff',
    qt_tip_t:'💡 This is for you if...', qt_tip_p:'You need a website, ERP, or AI solution but don\'t know where to start. You want to estimate the budget first. You\'re comparing multiple vendors. All are welcome — no pressure.',
    qt_contact_t:'📧 Quick Contact', qt_contact_p:'Feel free to reach out directly by email instead of the form.',
    qt_f_svc:'Select Services (multiple OK)', qt_f_basic:'Basic Information', qt_f_project:'Project Information',
    qt_f_company:'Company Name', qt_f_name:'Contact Person', qt_f_email:'Email', qt_f_phone:'Phone (optional)',
    qt_f_budget:'Budget Range', qt_bud0:'Please select', qt_bud1:'Under ₩5M', qt_bud2:'₩5M ~ ₩10M', qt_bud3:'₩10M ~ ₩30M', qt_bud4:'₩30M+', qt_bud5:'TBD / Negotiable',
    qt_f_schedule:'Target Completion', qt_sch0:'Please select', qt_sch1:'Within 1 month', qt_sch2:'1 ~ 3 months', qt_sch3:'3 ~ 6 months', qt_sch4:'6+ months', qt_sch5:'TBD / Negotiable',
    qt_f_desc:'Project Description', qt_agree:'I agree to the collection and use of personal information. Data will only be used for quote purposes and will not be shared with third parties.',
    qt_submit:'Send Quote Request', qt_ok_t:'Quote Request Received!', qt_ok_p:'Our team will contact you within 24 hours.', qt_ok_btn:'Back to Home',
    hero_badge:'IT Solution Specialist · Paju, Gyeonggi',
    hero_title:"Designing Tomorrow's<br>Business with Technology",
    hero_sub:'ERP · Web · ISMS · AI Solution Specialist',
    hero_cta1:'View Services', hero_cta2:'Contact Us', hero_scroll:'SCROLL',
    about_tag:'About Us', about_title:'Building the Future with Technology',
    about_desc:'AnthroMeta is an IT solution specialist founded in 2022 in Paju, Gyeonggi. We support every stage of enterprise digital transformation — from ERP and website development to ISMS consulting and AI-powered solutions.',
    about_lb1:'Founded', about_lv1:'April 2022',
    about_lb2:'Location', about_lv2:'Paju, Gyeonggi',
    about_lb3:'Industry', about_lv3:'IT Solutions',
    st1l:'Founded', st2l:'Projects Done', st3l:'Service Areas', st4l:'Satisfaction',
    svc_prev_tag:'SERVICES', svc_prev_title:'Our Services',
    svc_prev_desc:'Tailored solutions for your digital transformation',
    svc_link:'View All Services →',
    s1t:'ERP Solutions', s1p:'Custom ERP Build & Operations',
    s2t:'Website Development', s2p:'Corp · Hospital · Institution',
    s3t:'Catalog Design', s3p:'Brand Promotional Materials',
    s4t:'ISMS Consulting', s4p:'Information Security Certification',
    s5t:'AI Solutions', s5p:'Automation & AI Adoption',
    svc_tag:'SERVICES', svc_title:'Our Services',
    svc_desc:'Tailored solutions to accelerate your digital transformation',
    s1d:'We build custom ERP systems optimized for your environment — end-to-end from process analysis through deployment and ongoing support.',
    s1k1:'Custom Build', s1k2:'Process Optimization', s1k3:'Ongoing Support',
    s2d:'Professional websites for businesses, hospitals, and public institutions. Responsive design and SEO drive measurable results.',
    s2k1:'Corp / Hospital', s2k2:'Responsive', s2k3:'SEO',
    s3d:'Brand-aligned corporate materials planned and produced for impact — catalogs, brochures, leaflets, and more.',
    s3k1:'Branding', s3k2:'Print', s3k3:'Brochure',
    s4d:'Expert consulting for ISMS certification from gap analysis and policy development through audit readiness and full support.',
    s4k1:'Gap Analysis', s4k2:'Certification', s4k3:'Security Policy',
    s5d:'Business automation and AI adoption consulting. Enterprise-optimized AI solutions that boost productivity and competitive advantage.',
    s5k1:'Automation', s5k2:'AI Consulting', s5k3:'Productivity',
    cl_strip_tag:'CLIENTS', cl_strip_title:'Our Clients',
    cl_link:'View All Clients →',
    cl_tag:'CLIENTS', cl_title:'Our Clients',
    cl_desc:'Growing alongside companies across diverse industries',
    cl_hosp:'Medical / Hospitals', cl_neuro:'Korean Neurology Assoc.',
    cl_hosp_name:'Medical Institutions',
    cb_svc1:'Corporate Website', cb_svc2:'Video Production', cb_svc3:'Smart Farm Catalog+Site',
    cb_svc4:'Multi-lang Site · ERP', cb_svc5:'Catalog · IT MOU', cb_svc6:'Website', cb_svc7:'Website (Soon)',
    cl_trust:"AnthroMeta has built trust with leading companies including Noroo Holdings, The Giban, Giban Tech, Wooyoung Tech, and But&But, as well as numerous medical institutions. We deliver excellence regardless of industry or scale.",
    ref_tag:'REFERENCES', ref_title:'Project References', ref_desc:'Highlights from our delivered projects',
    rc1_cat:'Website Dev.', rc1_t1:'Corporate Site', rc1_t2:'Responsive', rc1_t3:'SEO',
    rc1_sub:'Corporate Website · Official Site for a Major Holding Company',
    rc1_desc:'We planned, designed, and built the official website for Noroo Holdings, a major holding company with subsidiaries including Noroo Paint and Noroo Auto Coating. Premium UI/UX reflects the brand identity across all devices.',
    rc1_l1:'Group subsidiary unified branding & pages', rc1_l2:'Responsive, mobile-first design',
    rc1_l3:'IR, newsroom & careers pages', rc1_l4:'Page speed optimization & SEO setup',
    rc2_cat:'Video Production', rc2_t1:'Corporate Promo', rc2_t2:'Filming & Editing', rc2_t3:'Motion Graphics',
    rc2_sub:'Video Production · Corporate Promotional Video',
    rc2_desc:"We handled the full production of The Giban's corporate promotional video — from storyboarding and on-site filming to professional editing with motion graphics, subtitles, and BGM.",
    rc2_l1:'Storyboard planning for corporate promo', rc2_l2:'On-site filming with professional equipment',
    rc2_l3:'Motion graphics, subtitles & BGM editing', rc2_l4:'Multi-format delivery: YouTube, SNS, PPT',
    rc3_cat:'Catalog + Website', rc3_t1:'Product Catalog', rc3_t2:'Corporate Site', rc3_t3:'B2B',
    rc3_sub:'Catalog Design + Website · Tech & Manufacturing Firm',
    rc3_desc:'We simultaneously delivered a product catalog and corporate website for Giban Tech, a manufacturing and IT specialist. B2B-focused design effectively communicates technical specs and product strengths.',
    rc3_l1:'Full product lineup catalog planning & production', rc3_l2:'B2B sales-optimized design & layout',
    rc3_l3:'Corporate website design & build', rc3_l4:'High-res files for both digital and print',
    rc4_cat:'Multilingual Site + Catalog', rc4_t1:'Multilingual Site', rc4_t2:'Catalog', rc4_t3:'ERP Upcoming',
    rc4_ongoing:'ERP In Progress',
    rc4_sub:'Multilingual Website + Catalog · ERP Implementation Upcoming',
    rc4_desc:'We built a trilingual (KO/EN/JP) website and English catalog for Wooyoung Tech targeting global markets. ERP implementation consulting is now underway for the next phase of digital transformation.',
    rc4_l1:'Trilingual website (KO/EN/JP) development', rc4_l2:'English product catalog for overseas buyers',
    rc4_l3:'Global SEO & international search visibility', rc4_l4:'Custom ERP implementation consulting (ongoing)',
    rc5_cat:'Catalog + IT MOU', rc5_t1:'Brand Catalog', rc5_t2:'Brochure', rc5_t3:'IT MOU',
    rc5_ongoing:'MOU Partner',
    rc5_sub:'Catalog Design · IT Consulting MOU · Strategic IT Partnership',
    rc5_desc:"We produced a comprehensive brand catalog for But&But and subsequently signed an MOU for IT consulting services, establishing a long-term strategic partnership for their digital transformation.",
    rc5_l1:'Full brand catalog planning & production', rc5_l2:'CMYK print + RGB digital dual delivery',
    rc5_l3:'IT Consulting MOU — strategic partnership', rc5_l4:'Joint digital transformation roadmap',
    rc6_cat:'Medical Website', rc6_t1:'Clinics & Hospitals', rc6_t2:'Booking Integration', rc6_t3:'Mobile-first',
    rc6_name:'Multiple Medical Clients',
    rc6_sub:'Medical Website · Clinics, Hospitals & Healthcare Providers',
    rc6_desc:'We have delivered websites for numerous medical providers across specialties — internal medicine, dermatology, dental, and traditional medicine — with patient-centric UX and online booking integration.',
    rc6_l1:'Patient-centered UX medical website builds', rc6_l2:'Specialty, staff & facility content pages',
    rc6_l3:'Online appointment booking integration', rc6_l4:'Healthcare law compliance & privacy design',
    rc7_cat:'Association Website', rc7_t1:'Medical Association', rc7_t2:'Institutional Site', rc7_t3:'Upcoming',
    rc7_ongoing:'In Preparation',
    rc7_name:'Korean Neurological Assoc.',
    rc7_sub:'Medical Association Website · Official site for a National Medical Body',
    rc7_desc:'We are preparing the official website for the Korean Neurological Association, representing neurology specialists nationwide. The site will integrate member management, academic resources, and conference schedules.',
    rc7_l1:'Official site for national neurology specialist body', rc7_l2:'Integrated member, academic & event platform',
    rc7_l3:'Dual UX for specialists & general public', rc7_l4:'Accessibility compliance + multilingual support',
    ind_h:'Expertise Across Industries',
    cta_title:'Ready to Start Your Project?',
    cta_desc:"Contact us without hesitation. We'll respond quickly and with care.",
    cta_btn:'Contact Us Now',
    qa_tag:'FAQ', qa_title:'Frequently Asked Questions', qa_desc:'Find answers to common questions',
    q1q:'How long does website development take?',
    q1a:'A typical corporate website takes approximately 4–8 weeks including planning, design, and development. Timeline varies by scope — hospitals or large institutions may need additional time. We provide an accurate schedule after the initial consultation.',
    q2q:'How much does ERP implementation cost?',
    q2a:'Costs vary significantly by company size, number of modules, and customization scope. We offer solutions for a wide range of budgets. Contact us for a precise quote after requirements analysis.',
    q3q:'How long does ISMS certification preparation take?',
    q3a:'Certification typically takes 6 months to 1 year depending on current state. Steps include gap analysis, policy development, control implementation, internal audits, and audit preparation. Our consultants provide hands-on support throughout.',
    q4q:'Can we sign a maintenance contract after launch?',
    q4a:'Yes. You can enter a monthly maintenance contract after launch covering content updates, security patches, incident response, and feature improvements — all in a plan customized to your needs.',
    q5q:'Can small startups request services?',
    q5a:"Of course. AnthroMeta serves companies of all sizes. We propose solutions that fit your budget and bring the same quality and commitment to every project. Don't hesitate to reach out.",
    ct_tag:'CONTACT', ct_title:'Contact Us',
    ct_desc:"Let's talk about your project. We respond quickly and with care.",
    ct_sub:'Start your consultation today', ct_kbtn:'Contact via KakaoTalk',
    ct_el:'Email', ct_pl:'Phone', ct_ll:'Location', ct_loc:'Paju, Gyeonggi, Korea',
    why_tag:'Why Choose Us', why_title:'Why AnthroMeta?', why_desc:'Your success is our commitment',
    why1_t:'Deep Expertise', why1_d:'Dedicated specialists in ERP, Web, ISMS, and AI handle every project from start to finish.',
    why2_t:'Proven Track Record', why2_d:'Trusted by Noroo Holdings and numerous enterprises and medical institutions.',
    why3_t:'Fast Start', why3_d:'Quick project kick-off after consultation, with strict deadline adherence.',
    why4_t:'Long-term Partner', why4_d:'We stay with you beyond delivery — maintaining and evolving your solution.',
    proc_tag:'PROCESS', proc_title:'How We Work',
    proc1_n:'01', proc1_t:'Free Consultation', proc1_d:'We analyze your business goals and requirements to define the project direction.',
    proc2_n:'02', proc2_t:'Planning & Design', proc2_d:'We design the optimal solution and present a detailed proposal and quote.',
    proc3_n:'03', proc3_t:'Development', proc3_d:'Our dedicated expert team builds with precision and high quality standards.',
    proc4_n:'04', proc4_t:'Delivery & Support', proc4_d:'High-quality delivery followed by continuous maintenance and upgrades.',
    s1b1:'Business process analysis & redesign', s1b2:'Module-level customization', s1b3:'Data migration & system integration', s1b4:'Staff training & operations support',
    s2b1:'Corp / hospital / institution expertise', s2b2:'Responsive & mobile-optimized design', s2b3:'SEO optimization & performance tuning', s2b4:'CMS integration & content management',
    s3b1:'Full brand identity alignment', s3b2:'Catalogs, brochures & leaflets', s3b3:'Digital & print dual-format files', s3b4:'Multilingual versions available',
    s4b1:'Gap analysis & roadmap planning', s4b2:'Security policy documentation', s4b3:'Employee information security training', s4b4:'Audit preparation & post-cert management',
    s5b1:'Business automation tool adoption', s5b2:'Chatbot & AI assistant setup', s5b3:'Data analytics & visualization systems', s5b4:'AI adoption strategy consulting',
    s6t:'Local LLM AI Solutions', s6p:'On-Premise AI · Fully Private',
    s6d:'Deploy and operate large language models (LLMs) entirely within your company — keeping all data on-site with zero external exposure. On-premise AI that works without cloud dependency, delivering both security and productivity.',
    s6k1:'On-Premise AI', s6k2:'Data Security', s6k3:'Custom Fine-tuning',
    s6b1:'On-site LLM deployment & GPU optimization', s6b2:'Domain-specific fine-tuning for your business',
    s6b3:'RAG system with internal docs & database', s6b4:'Air-gapped operation — zero data leakage',
    ind_h:'Expertise Across Industries',
    q6q:'How does the contract process work?',
    q6a:'After requirements analysis, we prepare a quote and contract. Payment is typically 50% upfront, 30% mid-project, and 20% on delivery — adjustable based on scope. Deliverables, timeline, and acceptance criteria are clearly defined in the contract.',
    q7q:'Can companies outside the Seoul metro area request services?',
    q7a:'Absolutely. While based in Paju, Gyeonggi, we serve clients nationwide via video conferencing and remote collaboration tools, delivering the same quality as in-person. On-site visits can also be arranged if needed.',
    q8q:'Can I see your portfolio or client references?',
    q8a:"Please reach out via KakaoTalk or email. We'll share relevant portfolio pieces and references within the bounds of any confidentiality agreements — as detailed as possible, categorized by industry.",
    ind_title:'Industries We Serve', ind1:'Manufacturing', ind2:'Healthcare', ind3:'IT / Software', ind4:'Distribution', ind5:'Public / Institution', ind6:'Startup',
    ct_hrs_title:'Business Hours', ct_hrs:'Mon – Fri  09:00 – 18:00\n(Closed weekends & holidays)',
    ct_resp_title:'Response Time', ct_resp:'Within 24 hours\nof business day inquiry',
    ft_co:'AnthroMeta', ft_loc:'Paju, Gyeonggi', ft_est:'Est. April 2022', ft_r:'All rights reserved.'
  },
  ja:{
    nav_home:'ホーム', nav_about:'会社紹介', nav_services:'サービス', nav_clients:'取引先', nav_blog:'ブログ', nav_qa:'Q&A', nav_contact:'お問い合わせ', nav_quote:'見積依頼',
    ab_tag:'ABOUT US', ab_title:'アンスロメタ紹介', ab_sub:'技術でビジネスの明日を設計するITソリューション専門企業',
    ab_mv_tag:'MISSION & VISION', ab_mv_title:'ミッションとビジョン',
    ab_mission_h:'🎯 ミッション', ab_mission_p:'中小・中堅企業が最新のIT技術によりデジタル変革を実現し、より高い競争力を身につけられるよう、実践的で持続可能なソリューションを提供します。',
    ab_vision_h:'🔭 ビジョン', ab_vision_p:'企業のデジタルトランスフォーメーションの旅で最も信頼されるITパートナーとして、AIとデータ駆動型ソリューションで産業全般のスマートイノベーションを牽引します。',
    ab_info_tag:'COMPANY', ab_info_title:'会社情報',
    ab_intro:'アンスロメタは2022年4月、韓国・京畿道坡州市に設立されたITソリューション専門企業です。ERP構築からウェブサイト制作、ISMSコンサルティング、AIソリューション、ローカルLLM構築まで、企業のデジタル変革を一貫してサポートします。',
    ab_intro2:'ノルホールディングス、ギバンテク、ウヨンテクなど製造・流通・医療分野の豊富なリファレンスを持ち、各業種に最適化されたITソリューションを迅速かつ正確に提供します。',
    ab_tl_tag:'HISTORY', ab_tl_title:'沿革', ab_tl_sub:'アンスロメタの成長の歩み',
    tl1_t:'アンスロメタ設立', tl1_d:'京畿道坡州市にてITソリューション専門企業として創業。ERPおよびウェブサイト制作事業を開始。',
    tl2_t:'ノルホールディングス ウェブサイト構築', tl2_d:'大企業系列の持株会社公式ウェブサイトを企画・設計・構築。初の大型リファレンスを獲得。',
    tl3_t:'製造業リファレンス拡大', tl3_d:'ギバンテク（スマートファーム）、ウヨンテク（多言語サイト）など製造・IT分野のリファレンスを多数獲得。',
    tl4_t:'ISMSコンサルティングサービス開始', tl4_d:'情報セキュリティ専門人材を採用し、ISMS・ISMS-P認証コンサルティングサービスを正式ローンチ。',
    tl5_t:'医療機関ウェブサイト多数納品', tl5_d:'病院・クリニック特化のウェブサイトソリューションを完成。大韓神経科協会と契約締結。',
    tl6_t:'ローカルLLM AIソリューション開始', tl6_d:'オンプレミス大規模言語モデル（LLM）構築サービスを開始。データセキュリティ重視企業向けAIソリューションを提供。',
    tl7_t:'継続成長中', tl7_d:'ERP・AI・LLM統合ソリューションを拡張し、新規パートナーシップを構築。より多くの企業のデジタル変革を支援します。',
    ab_val_tag:'CORE VALUES', ab_val_title:'コアバリュー', ab_val_sub:'アンスロメタの仕事の流儀',
    val1_t:'迅速性', val1_p:'迅速な納期と即時コミュニケーションで、ビジネスチャンスを逃さないようサポートします。',
    val2_t:'専門性', val2_p:'各分野の専門人材が企画から構築、運営まで最高水準の品質を保証します。',
    val3_t:'信頼性', val3_p:'100%プロジェクト完遂の原則と透明なコミュニケーションで、顧客と長期的なパートナーシップを維持します。',
    val4_t:'革新性', val4_p:'AI・LLMなど最新技術を迅速にビジネスへ適用し、競争優位性を創出します。',
    blog_tag:'INSIGHT & BLOG', blog_title:'ITインサイト', blog_sub:'AI・ERP・ウェブ開発・セキュリティ分野の最新トレンドと実務ノウハウ',
    cat_all:'すべて', cat_ai:'AI・LLM', cat_web:'ウェブ開発', cat_erp:'ERP', cat_sec:'セキュリティ',
    qt_tag:'QUOTE REQUEST', qt_title:'見積依頼', qt_sub:'プロジェクト情報をご入力いただければ、24時間以内にカスタム見積をお届けします',
    qt_proc_t:'🗓️ 見積プロセス', qt_s1:'フォーム記入・送信', qt_s2:'24時間以内に担当者からご連絡', qt_s3:'要件詳細ミーティング（オン/オフ）', qt_s4:'カスタム見積書を送付', qt_s5:'契約・プロジェクト着手',
    qt_tip_t:'💡 こんな方におすすめ', qt_tip_p:'ウェブサイト・ERP・AI導入が必要だが、どこから始めればよいかわからない方。予算を先に把握したい方。複数社の見積を比較したい方。お気軽にお問い合わせください。',
    qt_contact_t:'📧 直接お問い合わせ', qt_contact_p:'フォームの代わりにメールで直接お問い合わせいただいても構いません。',
    qt_f_svc:'サービス選択（複数選択可）', qt_f_basic:'基本情報', qt_f_project:'プロジェクト情報',
    qt_f_company:'会社名', qt_f_name:'担当者名', qt_f_email:'メールアドレス', qt_f_phone:'電話番号（任意）',
    qt_f_budget:'予算規模', qt_bud0:'選択してください', qt_bud1:'500万ウォン以下', qt_bud2:'500〜1,000万ウォン', qt_bud3:'1,000〜3,000万ウォン', qt_bud4:'3,000万ウォン以上', qt_bud5:'未定・協議',
    qt_f_schedule:'希望完了時期', qt_sch0:'選択してください', qt_sch1:'1ヶ月以内', qt_sch2:'1〜3ヶ月', qt_sch3:'3〜6ヶ月', qt_sch4:'6ヶ月以上', qt_sch5:'未定・協議',
    qt_f_desc:'プロジェクト内容', qt_agree:'個人情報の収集・利用に同意します。収集された情報は見積提供目的にのみ使用され、第三者への提供は行いません。',
    qt_submit:'見積依頼を送る', qt_ok_t:'見積依頼を受け付けました！', qt_ok_p:'24時間以内に担当者よりご連絡いたします。', qt_ok_btn:'ホームに戻る',
    hero_badge:'ITソリューション専門企業 · 京畿道坡州市',
    hero_title:'テクノロジーでビジネスの<br>未来を設計します',
    hero_sub:'ERP・ウェブ・ISMS・AIソリューション専門企業',
    hero_cta1:'サービスを見る', hero_cta2:'お問い合わせ', hero_scroll:'SCROLL',
    about_tag:'会社紹介', about_title:'テクノロジーで未来を切り拓く企業',
    about_desc:'アンスロメタは2022年に京畿道坡州市で設立されたITソリューション専門企業です。ERP構築からウェブサイト制作、ISMSコンサルティング、AIソリューションまで、企業のデジタルトランスフォーメーションを総合的に支援します。',
    about_lb1:'設立', about_lv1:'2022年4月',
    about_lb2:'所在地', about_lv2:'京畿道坡州市',
    about_lb3:'業種', about_lv3:'ITソリューション',
    st1l:'設立年', st2l:'完了PJ', st3l:'専門サービス', st4l:'顧客満足',
    svc_prev_tag:'サービス', svc_prev_title:'主要サービス',
    svc_prev_desc:'デジタルトランスフォーメーションを実現するソリューション',
    svc_link:'すべてのサービスを見る →',
    s1t:'ERPソリューション', s1p:'企業カスタムERP構築・運用',
    s2t:'ウェブサイト制作', s2p:'企業・病院・公共機関サイト',
    s3t:'カタログデザイン', s3p:'ブランドPR資料の企画・制作',
    s4t:'ISMSコンサルティング', s4p:'情報セキュリティ認証支援',
    s5t:'AIソリューション', s5p:'業務自動化・AI導入支援',
    svc_tag:'サービス', svc_title:'主要サービス',
    svc_desc:'企業のデジタルトランスフォーメーションを実現するソリューションを提供します',
    s1d:'企業環境に最適化されたカスタムERPシステムを構築します。業務プロセス分析から導入・運用サポートまで、ワンストップで提供します。',
    s1k1:'カスタム構築', s1k2:'プロセス最適化', s1k3:'運用サポート',
    s2d:'企業・病院・公共機関向けの専門サイトを構築します。レスポンシブデザインとSEO最適化でビジネス成果を高めます。',
    s2k1:'企業/病院/機関', s2k2:'レスポンシブ', s2k3:'SEO',
    s3d:'ブランドアイデンティティを反映した企業PR資料を企画・制作します。カタログ、パンフレット、リーフレットなど各種印刷物を制作します。',
    s3k1:'ブランディング', s3k2:'印刷物', s3k3:'パンフレット',
    s4d:'ISMS認証取得のための専門コンサルティングを提供します。ギャップ分析から審査対応まで全工程をサポートします。',
    s4k1:'ギャップ分析', s4k2:'認証支援', s4k3:'セキュリティポリシー',
    s5d:'業務自動化およびAI技術導入コンサルティングを提供します。企業に最適化されたAIソリューションで生産性と競争力を向上させます。',
    s5k1:'業務自動化', s5k2:'AIコンサルティング', s5k3:'生産性向上',
    cl_strip_tag:'取引先', cl_strip_title:'主要取引先',
    cl_link:'取引先をもっと見る →',
    cl_tag:'取引先', cl_title:'主要取引先',
    cl_desc:'さまざまな業界の企業と共に成長しています',
    cl_hosp:'医療/病院 多数', cl_neuro:'大韓神経科協会',
    cl_hosp_name:'医療機関 多数',
    cb_svc1:'法人サイト', cb_svc2:'映像制作', cb_svc3:'スマート農場 カタログ+サイト',
    cb_svc4:'多言語サイト · ERP', cb_svc5:'カタログ · IT MOU', cb_svc6:'ウェブサイト', cb_svc7:'ウェブサイト（準備中）',
    cl_trust:'アンスロメタはノルホールディングスをはじめ多数の企業・医療機関のウェブサイト制作を手がけ、信頼を積み重ねてきました。規模・業種を問わず最高のサービスを提供します。',
    ref_tag:'REFERENCES', ref_title:'プロジェクト実績', ref_desc:'アンスロメタが手がけた代表的なプロジェクトをご紹介します',
    rc1_cat:'ウェブサイト制作', rc1_t1:'企業サイト', rc1_t2:'レスポンシブ', rc1_t3:'SEO',
    rc1_sub:'Corporate Website · 大手持株会社の公式サイト',
    rc1_desc:'ノルペイント等多数の子会社を持つノルホールディングスの公式サイトを企画・設計・構築しました。',
    rc1_l1:'グループ会社統合ブランディングページ', rc1_l2:'レスポンシブ・モバイルファースト',
    rc1_l3:'IR・ニュースルーム・採用ページ', rc1_l4:'ページ速度最適化・SEO設定',
    rc2_cat:'映像制作', rc2_t1:'企業PR動画', rc2_t2:'撮影・編集', rc2_t3:'モーショングラフィック',
    rc2_sub:'Video Production · 企業PRビデオ制作',
    rc2_desc:'ザ・ギバンの企業PR動画を企画から最終納品まで全工程担当しました。',
    rc2_l1:'企業PRビデオのストーリーボード企画', rc2_l2:'プロ機材による現場撮影',
    rc2_l3:'モーショングラフィック・字幕・BGM編集', rc2_l4:'YouTube・SNS・PPT 複数フォーマット納品',
    rc3_cat:'カタログ+サイト', rc3_t1:'製品カタログ', rc3_t2:'企業サイト', rc3_t3:'B2B',
    rc3_sub:'Catalog Design + Website · 製造・技術専門企業',
    rc3_desc:'ギバンテックの製品カタログとウェブサイトを同時に制作・納品しました。',
    rc3_l1:'製品ラインナップ全体カタログ制作', rc3_l2:'B2B営業特化デザイン',
    rc3_l3:'企業ウェブサイト設計・構築', rc3_l4:'デジタル・印刷兼用高解像度ファイル',
    rc4_cat:'多言語サイト+カタログ', rc4_t1:'多言語サイト', rc4_t2:'カタログ', rc4_t3:'ERP準備中',
    rc4_ongoing:'ERP導入進行中',
    rc4_sub:'多言語ウェブサイト+カタログ · ERP導入準備中',
    rc4_desc:'グローバル市場向けに3言語対応（韓英日）のウェブサイトと英語カタログを制作。現在はERP導入コンサルティングを進めています。',
    rc4_l1:'韓国語・英語・日本語 多言語サイト構築', rc4_l2:'海外バイヤー向け英語カタログ制作',
    rc4_l3:'グローバルSEO・海外検索露出強化', rc4_l4:'カスタムERP導入コンサルティング（進行中）',
    rc5_cat:'カタログ+IT MOU', rc5_t1:'ブランドカタログ', rc5_t2:'パンフレット', rc5_t3:'IT MOU',
    rc5_ongoing:'MOUパートナー',
    rc5_sub:'カタログデザイン · ITコンサルティングMOU · 戦略的ITパートナーシップ',
    rc5_desc:'バット＆バットのブランドカタログを制作し、その後ITコンサルティング分野でMOUを締結、長期的な戦略的パートナーシップを構築しました。',
    rc5_l1:'ブランドカタログ全面企画・制作', rc5_l2:'印刷CMYK+デジタルRGBデュアル納品',
    rc5_l3:'ITコンサルティングMOU締結', rc5_l4:'デジタル変革ロードマップ共同策定',
    rc6_cat:'医療機関サイト', rc6_t1:'病院・クリニック', rc6_t2:'予約連動', rc6_t3:'モバイル最適化',
    rc6_name:'医療機関 多数',
    rc6_sub:'Medical Website · 病院・医院・クリニックサイト',
    rc6_desc:'内科・皮膚科・歯科・漢方医院など多様な診療科の医療機関サイトを多数制作・納品した実績があります。',
    rc6_l1:'患者中心UX医療サイト構築', rc6_l2:'診療科・医師・施設紹介ページ',
    rc6_l3:'オンライン予約システム連動', rc6_l4:'医療法遵守・個人情報保護設計',
    rc7_cat:'医療団体サイト', rc7_t1:'医療専門団体', rc7_t2:'機関サイト', rc7_t3:'準備中',
    rc7_ongoing:'制作準備中',
    rc7_name:'大韓神経科協会',
    rc7_sub:'Medical Association Website · 全国医療専門団体の公式サイト',
    rc7_desc:'全国の神経科専門医を代表する大韓神経科協会の公式サイト構築を準備しています。',
    rc7_l1:'全国神経科専門医協会の公式サイト構築', rc7_l2:'会員管理・学術情報・学会日程統合',
    rc7_l3:'専門家・一般向けデュアルUX設計', rc7_l4:'アクセシビリティ+多言語対応予定',
    ind_h:'多様な業界をカバーする専門性',
    cta_title:'プロジェクトを始める準備はできましたか？',
    cta_desc:'お気軽にお問い合わせください。迅速かつ丁寧にご回答します。',
    cta_btn:'今すぐお問い合わせ',
    qa_tag:'FAQ', qa_title:'よくある質問', qa_desc:'ご不明な点をご確認ください',
    q1q:'ウェブサイト制作にはどのくらいかかりますか？',
    q1a:'一般的な企業サイトの場合、企画・デザイン・開発を含め約4〜8週間かかります。プロジェクトの規模や要件によって異なり、病院や大規模機関の場合は追加時間が必要になることがあります。初回ご相談の際に正確なスケジュールをご案内します。',
    q2q:'ERP構築の費用はどのくらいですか？',
    q2a:'ERP構築費用は企業規模・モジュール数・カスタマイズの範囲によって大きく異なります。さまざまな予算に合わせたソリューションをご提案します。正確なお見積もりは要件定義後にご案内しますので、まずはお気軽にお問い合わせください。',
    q3q:'ISMS認証の準備にはどのくらいかかりますか？',
    q3a:'ISMS認証取得までは企業の現状に応じて通常6ヶ月〜1年程度かかります。ギャップ分析、ポリシー策定、管理策実装、内部監査、審査対応などのプロセスを経ます。専門コンサルタントが全工程を密着サポートします。',
    q4q:'サイト構築後の保守契約は可能ですか？',
    q4a:'はい、可能です。サイト構築完了後に月額保守契約を締結いただけます。コンテンツ更新、セキュリティパッチ、障害対応、機能改善などを含むカスタマイズされた保守プランを提供しています。',
    q5q:'小規模スタートアップでも依頼できますか？',
    q5a:'もちろんです。アンスロメタはスタートアップから中堅企業まで規模を問わずサービスを提供しています。予算と要件に最適なソリューションをご提案し、どんなプロジェクトにも同じ品質と情熱で取り組みます。お気軽にご相談ください。',
    ct_tag:'お問い合わせ', ct_title:'お問い合わせ',
    ct_desc:'プロジェクトについてお話しください。迅速かつ丁寧にご回答します。',
    ct_sub:'今すぐご相談を始めましょう', ct_kbtn:'カカオトークでお問い合わせ',
    ct_el:'メール', ct_pl:'電話', ct_ll:'所在地', ct_loc:'韓国 京畿道坡州市',
    why_tag:'選ばれる理由', why_title:'なぜアンスロメタか？', why_desc:'お客様の成功が私たちの使命です',
    why1_t:'専門性', why1_d:'ERP・ウェブ・ISMS・AI各分野の専任スペシャリストが最初から最後まで担当します。',
    why2_t:'実績と信頼', why2_d:'ノルホールディングスをはじめ多数の企業・医療機関への納品実績があります。',
    why3_t:'迅速な着手', why3_d:'ご相談後の素早いスケジュール設定と納期厳守を最優先にします。',
    why4_t:'長期パートナー', why4_d:'納品後も保守・アップグレードで長期的にサポートし続けます。',
    proc_tag:'プロセス', proc_title:'プロジェクトの進め方',
    proc1_n:'01', proc1_t:'無料相談', proc1_d:'ビジネス目標と要件を丁寧にヒアリングし、プロジェクトの方向性を定めます。',
    proc2_n:'02', proc2_t:'企画・設計', proc2_d:'最適なソリューションを設計し、詳細な提案書と見積書を作成します。',
    proc3_n:'03', proc3_t:'開発・構築', proc3_d:'専任チームが高品質な基準で開発・実装を行います。',
    proc4_n:'04', proc4_t:'納品・サポート', proc4_d:'高品質な納品と継続的なアフターサポート・アップグレードを提供します。',
    s1b1:'業務プロセス分析・再設計', s1b2:'モジュール別カスタマイズ', s1b3:'データ移行・システム連携', s1b4:'従業員研修・運用サポート',
    s2b1:'企業・病院・機関サイト専門', s2b2:'レスポンシブ・モバイル最適化', s2b3:'SEO最適化・パフォーマンスチューニング', s2b4:'CMS連携・コンテンツ管理',
    s3b1:'ブランドアイデンティティの完全反映', s3b2:'カタログ・パンフレット・リーフレット', s3b3:'デジタル・印刷デュアル制作', s3b4:'多言語版制作対応',
    s4b1:'ギャップ分析・ロードマップ策定', s4b2:'セキュリティポリシー文書化', s4b3:'従業員セキュリティ教育', s4b4:'審査対応・認証後管理',
    s5b1:'業務自動化ツール導入支援', s5b2:'チャットボット・AIアシスタント構築', s5b3:'データ分析・可視化システム', s5b4:'AI導入戦略コンサルティング',
    s6t:'ローカルLLM AIソリューション', s6p:'オンプレミスAI · 完全プライベート',
    s6d:'大規模言語モデル（LLM）を社内サーバーで直接構築・運用し、データを外部に一切出さない完全プライベートAI環境を提供します。クラウド不要のオンプレミスAIでセキュリティと生産性を同時に確保します。',
    s6k1:'オンプレミスAI', s6k2:'データセキュリティ', s6k3:'カスタムFine-tuning',
    s6b1:'社内サーバーLLM構築・GPU最適化', s6b2:'事業ドメイン特化ファインチューニング',
    s6b3:'社内文書・DB連携RAGシステム構築', s6b4:'完全クローズド運用 — データ漏洩ゼロ',
    rc1_t1:'塗料・化学持株会社', rc3_t1:'スマートファーム専門企業',
    ind_h:'多様な業界をカバーする専門性',
    q6q:'契約はどのように進みますか？',
    q6a:'要件定義後、見積書と契約書を作成します。支払いは一般的に着手金50%・中間金30%・残金20%ですが、規模に応じて協議可能です。契約書には成果物・スケジュール・検収基準が明確に記載されます。',
    q7q:'地方の企業でも依頼できますか？',
    q7a:'もちろんです。京畿道坡州を拠点としていますが、ビデオ会議とリモートツールで全国対応が可能です。対面と変わらない品質のサービスを提供し、必要に応じて訪問対応も協議できます。',
    q8q:'ポートフォリオや実績は確認できますか？',
    q8a:'カカオトークまたはメールでご連絡ください。守秘義務の範囲内で業種別ポートフォリオと実績をできる限り詳しくご案内します。',
    ind_title:'対応業種', ind1:'製造業', ind2:'医療・バイオ', ind3:'IT・ソフトウェア', ind4:'流通・物流', ind5:'公共・機関', ind6:'スタートアップ',
    ct_hrs_title:'営業時間', ct_hrs:'平日 09:00 – 18:00\n（土日・祝日は休業）',
    ct_resp_title:'返答時間', ct_resp:'お問い合わせ後\n24時間以内にご回答',
    ft_co:'アンスロメタ', ft_loc:'京畿道坡州市', ft_est:'設立 2022年4月', ft_r:'All rights reserved.'
  }
};

let lang = localStorage.getItem('am-lang') || 'ko';

function setLang(l) {
  lang = l;
  localStorage.setItem('am-lang', l);
  document.documentElement.lang = {ko:'ko',en:'en',ja:'ja'}[l];
  document.body.className = 'lang-' + l;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    if (el.hasAttribute('data-notrans')) return;
    const v = T[l][el.getAttribute('data-i18n')];
    if (v != null) el.innerHTML = v;
  });
  ['ko','en','ja'].forEach(x => {
    const b = document.getElementById('b'+x);
    if (b) b.classList.toggle('active', x === l);
  });
}

/* Active nav */
function initNav() {
  const page = window.location.pathname.split('/').pop() || 'index.html';
  document.querySelectorAll('a[data-page]').forEach(a => {
    const p = a.getAttribute('data-page');
    a.classList.toggle('active-link', p === page || (page === '' && p === 'index.html'));
  });
}

/* Header scroll */
window.addEventListener('scroll', () => {
  const h = document.getElementById('hdr');
  if (h) h.classList.toggle('scrolled', scrollY > 20);
});

/* Mobile menu */
function toggleMenu() {
  document.getElementById('mnav').classList.toggle('open');
  document.getElementById('burg').classList.toggle('open');
}
function closeMenu() {
  document.getElementById('mnav').classList.remove('open');
  document.getElementById('burg').classList.remove('open');
}

/* FAQ */
function toggleFaq(btn) {
  const item = btn.parentElement;
  const wasOpen = item.classList.contains('open');
  document.querySelectorAll('.fi').forEach(i => i.classList.remove('open'));
  if (!wasOpen) item.classList.add('open');
}

/* Scroll reveal */
function initReveal() {
  const obs = new IntersectionObserver(entries => {
    entries.forEach(e => { if (e.isIntersecting) e.target.classList.add('vis'); });
  }, { threshold: 0.08, rootMargin: '0px 0px -40px 0px' });
  document.querySelectorAll('.reveal').forEach(el => obs.observe(el));
}

/* Init */
document.addEventListener('DOMContentLoaded', () => {
  setLang(lang);
  initNav();
  initReveal();
  // trigger scroll check for already-scrolled state on reload
  if (scrollY > 20) {
    const h = document.getElementById('hdr');
    if (h) h.classList.add('scrolled');
  }
});
