/* AnthroMeta — anthrometa.com — Shared JS */

const T = {
  ko:{
    nav_home:'홈', nav_about:'회사소개', nav_services:'서비스', nav_clients:'거래처', nav_blog:'블로그', nav_qa:'Q&A', nav_contact:'문의하기', nav_quote:'견적문의', sc_cta:'이 서비스 문의하기 →',
    /* About */
    ab_tag:'ABOUT US', ab_title:'앤트로메타 소개', ab_sub:'기술로 비즈니스의 내일을 설계하는 IT 솔루션 전문기업',
    ab_mv_tag:'MISSION & VISION', ab_mv_title:'미션과 비전',
    ab_mission_h:'🎯 미션', ab_mission_p:'중소·중견기업이 최신 IT 기술을 통해 디지털 혁신을 이루고, 더 나은 경쟁력을 갖출 수 있도록 실질적이고 지속 가능한 솔루션을 제공합니다.',
    ab_vision_h:'🔭 비전', ab_vision_p:'기업의 디지털 전환 여정에서 가장 신뢰받는 IT 파트너로 자리매김하며, AI와 데이터 기반 솔루션으로 산업 전반의 스마트 혁신을 이끌어 나갑니다.',
    ab_info_tag:'COMPANY', ab_info_title:'회사 정보',
    ab_intro:'앤트로메타는 2022년 경기도 파주시에서 설립된 IT 솔루션 전문기업입니다. ERP 구축부터 홈페이지 제작, ISMS 컨설팅, 취약점 점검·모의해킹, 로컬 LLM 구축까지 기업 디지털 혁신의 전 단계를 원스톱으로 지원합니다.',
    ab_intro2:'GS리테일, LS산전, 기반테크, 우영테크 등 제조·유통·보안 분야 다양한 기업과의 실전 레퍼런스를 바탕으로, 각 업종에 최적화된 IT 솔루션을 빠르고 정확하게 납품합니다.',
    ab_tl_tag:'HISTORY', ab_tl_title:'연혁', ab_tl_sub:'앤트로메타의 성장 여정',
    tl1_t:'앤트로메타 설립', tl1_d:'경기도 파주시에서 IT 솔루션 전문기업으로 창업. ERP 및 홈페이지 제작 사업 개시.',
    tl2_t:'GS리테일 보안 취약점 점검', tl2_d:'대기업 유통사 보안 취약점 점검 프로그램 수행. 첫 대형 레퍼런스 확보.',
    tl3_t:'제조업 레퍼런스 확장', tl3_d:'기반테크(스마트팜), 우영테크(다국어 홈피) 등 제조·IT 분야 레퍼런스 다수 확보.',
    tl4_t:'ISMS 컨설팅 서비스 출시', tl4_d:'정보보안 전문 인력 영입, ISMS·ISMS-P 인증 컨설팅 서비스 공식 런칭.',
    tl5_t:'의료기관 홈페이지 다수 납품', tl5_d:'병원·의원·클리닉 등 의료기관 특화 홈페이지 솔루션 완성. 대한신경과협회 계약 체결.',
    tl6_t:'로컬 LLM AI 솔루션 서비스 론칭', tl6_d:'온프레미스 대형언어모델(LLM) 구축 서비스 개시. 데이터 보안이 중요한 기업 대상 AI 솔루션 제공.',
    tl7_t:'지속 성장 중', tl7_d:'ERP·AI·LLM 통합 솔루션 확장 및 신규 파트너십 구축. 더 많은 기업의 디지털 혁신을 지원합니다.',
    ab_val_tag:'CORE VALUES', ab_val_title:'핵심 가치', ab_val_sub:'앤트로메타가 일하는 방식',
    val1_t:'신속성', val1_p:'빠른 납기와 즉각적인 커뮤니케이션으로 비즈니스 기회를 놓치지 않도록 지원합니다.',
    val2_t:'전문성', val2_p:'각 분야 전문 인력이 기획부터 구축, 운영까지 최고 수준의 품질을 보장합니다.',
    val3_t:'신뢰성', val3_p:'100% 프로젝트 완수 원칙과 투명한 소통으로 고객과 장기적 파트너십을 유지합니다.',
    val4_t:'혁신성', val4_p:'AI·LLM 등 최신 기술을 빠르게 비즈니스에 적용하여 경쟁 우위를 창출합니다.',
    /* Blog */
    blog_tag:'INSIGHT & BLOG', blog_title:'IT 인사이트', blog_sub:'AI · ERP · 웹개발 · 보안 분야의 최신 트렌드와 실무 노하우',
    cat_all:'전체', cat_ai:'AI · LLM', cat_web:'웹개발', cat_erp:'ERP', cat_sec:'보안',
    /* Quote */
    qt_tag:'QUOTE REQUEST', qt_title:'견적 문의', qt_sub:'프로젝트 정보를 입력해 주시면 24시간 이내 맞춤 견적을 제공합니다',
    qt_proc_t:'🗓️ 견적 프로세스', qt_s1:'양식 작성 & 제출', qt_s2:'24시간 이내 담당자 연락', qt_s3:'요구사항 상세 미팅 (온/오프)', qt_s4:'맞춤 견적서 발송', qt_s5:'계약 & 프로젝트 착수',
    qt_tip_t:'💡 이런 분께 추천', qt_tip_p:'홈페이지·ERP·AI 도입이 필요하지만 어디서 시작해야 할지 모르는 분, 예산을 먼저 파악하고 싶은 분 모두 환영합니다.',
    qt_contact_t:'📧 빠른 문의', qt_contact_p:'양식 대신 이메일로 바로 문의하셔도 됩니다.',
    qt_f_svc:'서비스 선택 (복수 선택 가능)', qt_f_basic:'기본 정보', qt_f_project:'프로젝트 정보',
    qt_f_company:'회사명', qt_f_name:'담당자명', qt_f_email:'이메일', qt_f_phone:'연락처 (선택)',
    qt_f_budget:'예산 범위', qt_bud0:'선택하세요', qt_bud1:'500만원 이하', qt_bud2:'500 ~ 1,000만원', qt_bud3:'1,000 ~ 3,000만원', qt_bud4:'3,000만원 이상', qt_bud5:'미정 / 협의',
    qt_f_schedule:'희망 완료 시기', qt_sch0:'선택하세요', qt_sch1:'1개월 이내', qt_sch2:'1 ~ 3개월', qt_sch3:'3 ~ 6개월', qt_sch4:'6개월 이상', qt_sch5:'미정 / 협의',
    qt_f_desc:'프로젝트 내용', qt_agree:'개인정보 수집 및 이용에 동의합니다. 수집된 정보는 견적 제공 목적으로만 사용되며, 제3자에게 제공되지 않습니다. <a href="privacy.html" style="color:var(--teal);text-decoration:underline" target="_blank">개인정보처리방침 보기</a>',
    qt_submit:'견적 요청 보내기', qt_ok_t:'견적 요청이 접수됐습니다!', qt_ok_p:'24시간 이내에 담당자가 연락드리겠습니다.', qt_ok_btn:'홈으로 돌아가기',
    /* Hero */
    hero_badge:'IT 솔루션 전문기업 · 경기도 파주',
    hero_title:'기술로 비즈니스의<br>내일을 설계합니다',
    hero_sub:'ERP · 홈페이지 · ISMS · AI · 로컬 LLM 솔루션 전문기업',
    hero_cta1:'서비스 보기', hero_cta2:'문의하기', hero_scroll:'SCROLL',
    /* About */
    about_tag:'회사 소개', about_title:'기술로 미래를 여는 기업',
    about_desc:'앤트로메타는 2022년 경기도 파주에서 설립된 이래, 대기업부터 중소기업, 병원과 공공기관까지 다양한 규모와 업종의 고객사와 함께 성장해온 IT 솔루션 전문기업입니다. ERP 구축, 웹사이트 제작, 카탈로그 디자인 같은 실무형 프로젝트부터 ISMS 인증 컨설팅, 취약점 점검·모의해킹, 로컬 LLM 기반 AI 솔루션까지 — 기업이 디지털 전환 과정에서 마주치는 문제를 기획부터 구축, 운영까지 한 팀이 책임지고 해결합니다. "만들어 드리고 끝"이 아니라, 납품 이후에도 계속 함께하는 파트너가 되는 것을 원칙으로 합니다.',
    about_lb1:'설립', about_lv1:'2022년 4월',
    about_lb2:'소재지', about_lv2:'경기도 파주시',
    about_lb3:'업종', about_lv3:'IT 솔루션',
    /* Stats */
    st1l:'설립 연도', st2l:'완료 프로젝트', st3l:'전문 서비스', st4l:'고객 만족',
    /* Services preview */
    svc_prev_tag:'SERVICES', svc_prev_title:'주요 서비스',
    svc_prev_desc:'기업의 디지털 혁신을 위한 맞춤형 솔루션',
    svc_link:'모든 서비스 보기 →',
    s1t:'ERP 솔루션', s1p:'기업 맞춤형 ERP 구축 · 운영',
    s2t:'홈페이지 제작', s2p:'기업·병원·기관 웹사이트',
    s3t:'카탈로그 디자인', s3p:'브랜드 홍보물 기획·제작',
    s4t:'ISMS 컨설팅', s4p:'정보보안 인증 취득 지원',
    s5t:'취약점 점검 · 모의해킹', s5p:'AI 기반 분석 · 실전 침해 시나리오',
    /* Services page detail */
    svc_tag:'SERVICES', svc_title:'주요 사업 영역',
    svc_desc:'기업의 디지털 혁신을 위한 맞춤형 솔루션을 제공합니다',
    s1d:'표준 패키지로는 채워지지 않는 기업 고유의 업무 흐름을 그대로 반영한 맞춤형 ERP를 구축합니다. 재고·회계·인사·생산 등 필요한 모듈만 선별해 설계하고, 기존에 엑셀과 수기로 처리하던 업무를 최소한의 혼란으로 시스템에 이식합니다. 도입 후에도 현장 담당자 교육과 장애 대응까지 책임지고 지원해, 만들고 끝나는 게 아니라 실제로 쓰이는 ERP를 만듭니다.',
    s1k1:'맞춤형 구축', s1k2:'프로세스 최적화', s1k3:'운영 지원',
    s2d:'기업 소개 사이트부터 병원 예약 연동, 공공기관 접근성 기준 준수까지 목적에 맞춰 기획 단계부터 함께 설계합니다. 모바일·태블릿·데스크톱 어디서도 무너지지 않는 반응형 구조와, 네이버·구글 검색에 실제로 노출되도록 만드는 SEO 기본기를 모든 프로젝트에 기본 적용합니다. 오픈 이후에도 콘텐츠 업데이트와 운영 지원을 이어가 "만들어두기만 한 사이트"가 되지 않게 합니다.',
    s2k1:'기업/병원/기관', s2k2:'반응형', s2k3:'SEO',
    s3d:'제품과 서비스의 강점을 처음 보는 사람도 한눈에 이해하도록 스토리 구조부터 설계한 뒤 카탈로그·브로슈어·리플렛으로 완성합니다. 인쇄용 고해상도 CMYK 파일과 온라인 배포용 디지털 파일을 함께 제공해 전시회·영업 미팅·웹사이트 어디서든 바로 활용할 수 있습니다. 해외 바이어 대응이 필요한 기업을 위한 다국어 버전 제작도 함께 지원합니다.',
    s3k1:'브랜딩', s3k2:'인쇄물', s3k3:'브로슈어',
    s4d:'ISMS 인증이 처음인 기업도 무엇부터 준비해야 할지 헤매지 않도록, 현재 보안 수준을 진단하는 갭분석부터 시작합니다. 부족한 부분을 채우는 보안 정책·지침 수립, 임직원 교육, 인증심사 대응까지 취득 전 과정을 함께하며, 인증 이후 사후관리 심사 대응까지 책임집니다. 규제 대응용 서류가 아니라 실제로 작동하는 보안체계를 만드는 것이 목표입니다.',
    s4k1:'갭분석', s4k2:'인증 지원', s4k3:'보안정책',
    s5d:'웹·앱·서버 전반을 대상으로 실제 해커가 쓰는 침투 기법을 그대로 재현해 보안 취약점을 검증합니다. AI 기반 자동화 분석으로 넓은 범위를 빠르게 스캔하고, 발견된 지점은 사람이 직접 침투 시나리오를 설계해 실전 수준으로 검증하는 방식을 함께 씁니다. 점검으로 끝나지 않고 위험도별 우선순위와 구체적 개선 방안까지 담은 리포트를 제공해, 다음에 무엇부터 고쳐야 할지 바로 알 수 있게 합니다.',
    s5k1:'취약점 점검', s5k2:'모의해킹', s5k3:'보안 컨설팅',
    /* Clients */
    cl_strip_tag:'CLIENTS', cl_strip_title:'주요 거래처',
    cl_link:'거래처 더보기 →',
    cl_tag:'CLIENTS', cl_title:'주요 거래처',
    cl_desc:'다양한 산업 분야의 기업들과 함께 성장하고 있습니다',
    cl_hosp:'의료/병원 다수', cl_neuro:'대한신경과협회',
    cl_hosp_name:'의료기관 다수',
    cb_svc1:'보안 취약점 점검', cb_svc2:'농생명 영상제작', cb_svc3:'스마트팜 카탈+홈피',
    cb_svc4:'다국어 홈피 · ERP', cb_svc5:'카탈로그 · IT MOU', cb_svc6:'홈페이지 제작', cb_svc7:'홈페이지 준비중',
    cb_svc8:'모의해킹', cb_svc9:'홈페이지 제작', cb_svc10:'프랜차이즈 홈페이지',
    cl_trust:'앤트로메타는 GS리테일, LS산전, 더기반, 기반테크, 우영테크, 벗앤벗, 바오비어 등 다양한 기업 및 다수의 의료기관 홈페이지를 제작·납품하며 신뢰를 쌓아왔습니다. 규모와 업종을 불문하고 최고의 서비스를 제공합니다.',
    /* Reference cards */
    ref_tag:'REFERENCES', ref_title:'프로젝트 레퍼런스', ref_desc:'앤트로메타가 함께한 대표 프로젝트를 소개합니다',
    rc1_cat:'보안 취약점 점검', rc1_t1:'유통 대기업', rc1_t2:'취약점 점검', rc1_t3:'보안 컨설팅',
    rc1_sub:'Security Assessment · 취약점 점검 프로그램',
    rc1_desc:'국내 대형 유통기업 GS리테일의 IT 인프라 및 서비스 전반에 대한 보안 취약점 점검 프로그램을 수행하였습니다. 웹·앱·서버 환경을 대상으로 체계적인 취약점 진단을 진행하고, 발견된 보안 이슈에 대한 상세 리포트와 우선순위별 개선 방안을 제시하여 정보보호 수준을 한층 강화하였습니다.',
    rc1_l1:'웹·앱·서버 전반 보안 취약점 진단', rc1_l2:'취약점별 위험도 평가 및 개선 가이드 제공',
    rc1_l3:'상세 점검 결과 리포트 작성', rc1_l4:'정기 점검 체계 수립 지원',
    rc2_cat:'영상 제작', rc2_t1:'기업 홍보 영상', rc2_t2:'촬영·편집', rc2_t3:'모션 그래픽',
    rc2_sub:'Video Production · 기업 홍보 영상 제작',
    rc2_desc:'㈜ 더기반의 브랜드 가치와 핵심 역량을 효과적으로 전달하는 기업 홍보 영상을 기획부터 최종 납품까지 전 과정을 담당하였습니다.',
    rc2_l1:'기업 홍보 영상 스토리보드 기획', rc2_l2:'전문 장비 활용 현장 촬영 진행',
    rc2_l3:'모션 그래픽·자막·BGM 삽입 편집', rc2_l4:'유튜브·SNS·PPT 다중 포맷 납품',
    rc3_cat:'카탈로그 + 홈페이지', rc3_t1:'제품 카탈로그', rc3_t2:'기업 홈페이지', rc3_t3:'B2B 특화',
    rc3_sub:'Catalog Design + Website · 제조·기술 전문기업',
    rc3_desc:'기술력 중심의 제조·IT 전문기업 ㈜ 기반테크의 제품 카탈로그 제작과 기업 홈페이지 구축을 동시에 진행하였습니다.',
    rc3_l1:'제품 라인업 전체 카탈로그 기획·제작', rc3_l2:'B2B 영업 특화 디자인 및 레이아웃',
    rc3_l3:'기업 홈페이지 설계 및 구축', rc3_l4:'디지털·인쇄 겸용 고해상도 파일 납품',
    rc4_cat:'카탈로그 + 다국어 홈페이지', rc4_t1:'다국어 홈페이지', rc4_t2:'카탈로그 제작', rc4_t3:'ERP 준비중',
    rc4_ongoing:'ERP 도입 진행중',
    rc4_sub:'Multilingual Website + Catalog · ERP Implementation (Upcoming)',
    rc4_desc:'글로벌 시장을 타깃으로 하는 우영테크의 다국어 홈페이지와 해외 바이어용 영문 제품 카탈로그를 제작하였습니다. 현재는 맞춤형 ERP 시스템 도입을 앤트로메타와 함께 준비하고 있습니다.',
    rc4_l1:'한국어·영어·일본어 다국어 홈페이지 구축', rc4_l2:'해외 바이어 대상 영문 제품 카탈로그 제작',
    rc4_l3:'글로벌 SEO 최적화 및 해외 검색 노출 강화', rc4_l4:'맞춤형 ERP 시스템 도입 컨설팅 진행중',
    rc5_cat:'카탈로그 + IT MOU', rc5_t1:'브랜드 카탈로그', rc5_t2:'브로슈어', rc5_t3:'IT 컨설팅 MOU',
    rc5_ongoing:'MOU 파트너',
    rc5_sub:'Catalog Design · IT Consulting MOU · 전략적 IT 파트너십',
    rc5_desc:'㈜ 벗앤벗의 브랜드 정체성을 담은 제품·서비스 카탈로그를 전면 기획·제작하였습니다. 납품 이후 IT 컨설팅 분야 MOU(양해각서)를 체결, 디지털 전환 전반에 걸친 전략적 IT 파트너십을 구축하였습니다.',
    rc5_l1:'브랜드 아이덴티티 반영 카탈로그 전면 기획·제작', rc5_l2:'인쇄용 CMYK + 디지털 RGB 이중 포맷 납품',
    rc5_l3:'IT 컨설팅 분야 MOU 체결 — 전략적 파트너십', rc5_l4:'디지털 전환 로드맵 공동 수립 및 지속 협력',
    rc6_cat:'의료기관 홈페이지', rc6_t1:'병원·의원', rc6_t2:'진료 예약 연동', rc6_t3:'모바일 최적화',
    rc6_name:'의료기관 다수',
    rc6_sub:'Medical Website · 병원·의원·클리닉 홈페이지',
    rc6_desc:'내과, 피부과, 치과, 한의원 등 다양한 진료과목의 의료기관 홈페이지를 다수 제작·납품한 실적을 보유하고 있습니다.',
    rc6_l1:'환자 중심 UX 기반 의료 홈페이지 구축', rc6_l2:'진료과목·의료진·시설 소개 콘텐츠 구성',
    rc6_l3:'온라인 예약 시스템 연동', rc6_l4:'의료법 준수·개인정보보호 설계 기본 탑재',
    rc7_cat:'의료단체 홈페이지', rc7_t1:'의료 전문 단체', rc7_t2:'기관 홈페이지', rc7_t3:'준비중',
    rc7_ongoing:'제작 준비중',
    rc7_name:'대한신경과협회',
    rc7_sub:'Medical Association Website · 전문 의료단체 공식 홈페이지',
    rc7_desc:'대한민국 신경과 전문의를 대표하는 대한신경과협회의 공식 홈페이지 구축을 준비하고 있습니다.',
    rc7_l1:'전국 신경과 전문의 대표 협회 공식 홈페이지 구축', rc7_l2:'회원 관리·학술 정보·학회 일정 통합 플랫폼 설계',
    rc7_l3:'의료 전문가·일반인 대상 이중 UX 구조 설계', rc7_l4:'접근성 + 다국어 지원 적용 예정',
    rc8_cat:'모의해킹', rc8_t1:'전기·전력 제조기업', rc8_t2:'모의해킹', rc8_t3:'침해 시나리오 분석',
    rc8_sub:'Penetration Testing · 모의해킹 보안 진단',
    rc8_desc:'전기·전력 설비 전문기업 LS산전을 대상으로 실제 공격 기법을 활용한 모의해킹을 수행하였습니다. 외부 침투, 내부 권한 상승, 주요 시스템 접근 가능성 등 실전 침해 시나리오를 기반으로 보안 취약점을 검증하고, 대응 방안을 포함한 종합 보안 진단 결과를 제공하였습니다.',
    rc8_l1:'실전 공격 기법 기반 모의해킹 수행', rc8_l2:'외부 침투·내부 권한 상승 시나리오 검증',
    rc8_l3:'주요 시스템 접근 가능성 분석', rc8_l4:'대응 방안 포함 종합 보안 진단 리포트 제공',
    rc9_cat:'홈페이지 제작', rc9_t1:'노인복지 기관', rc9_t2:'기관 홈페이지', rc9_t3:'접근성 디자인',
    rc9_sub:'Institutional Website · 노인복지기관 공식 홈페이지',
    rc9_desc:'고양 시니어 클럽의 공식 홈페이지를 기획·설계·구축하였습니다. 어르신과 보호자 모두가 쉽게 이용할 수 있도록 큰 글씨·고대비 컬러 등 접근성을 고려한 UI를 적용하였으며, 기관 소개·프로그램 안내·공지사항 등을 직관적으로 구성하여 지역 주민들의 이용 편의성을 높였습니다.',
    rc9_l1:'노인복지기관 특화 접근성 UI/UX 적용', rc9_l2:'프로그램·공지사항 안내 콘텐츠 구성',
    rc9_l3:'모바일 최적화 반응형 디자인 적용', rc9_l4:'지역 주민 대상 이용 편의성 강화',
    rc10_cat:'프랜차이즈 홈페이지', rc10_t1:'외식 프랜차이즈', rc10_t2:'가맹점 안내', rc10_t3:'브랜드 홈페이지',
    rc10_sub:'Franchise Website · 프랜차이즈 브랜드 홈페이지 구축',
    rc10_desc:'외식 프랜차이즈 브랜드 바오비어의 공식 홈페이지를 기획·설계·구축하였습니다. 브랜드 스토리·메뉴 소개·매장 안내와 함께 가맹 문의 기능을 포함하여 신규 가맹점주 유입을 지원하였으며, 브랜드 톤앤매너를 일관성 있게 적용한 비주얼로 고객 신뢰도를 높였습니다.',
    rc10_l1:'브랜드 스토리·메뉴·매장 안내 콘텐츠 구성', rc10_l2:'가맹 문의 기능 탑재로 신규 가맹점주 유입 지원',
    rc10_l3:'브랜드 톤앤매너 반영 비주얼 디자인 적용', rc10_l4:'모바일 최적화 반응형 디자인 적용',
    ind_h:'다양한 산업에 걸친 전문성',
    /* CTA */
    cta_title:'프로젝트를 시작할 준비가 되셨나요?',
    cta_desc:'부담 없이 문의해 주세요. 빠르고 친절하게 답변드립니다.',
    cta_btn:'지금 문의하기',
    /* Q&A */
    qa_tag:'FAQ', qa_title:'자주 묻는 질문', qa_desc:'궁금하신 사항을 확인해보세요',
    q1q:'홈페이지 제작 기간은 얼마나 걸리나요?',
    q1a:'일반적인 기업 홈페이지의 경우 기획·디자인·개발을 포함하여 약 4~8주가 소요됩니다. 프로젝트의 규모와 요구사항에 따라 기간이 달라질 수 있으며, 병원이나 대형 기관의 경우 추가 기간이 필요할 수 있습니다. 초기 상담을 통해 정확한 일정을 안내해 드립니다.',
    q2q:'ERP 구축 비용은 어떻게 되나요?',
    q2a:'ERP 구축 비용은 기업 규모, 필요한 모듈 수, 커스터마이징 범위에 따라 크게 달라집니다. 소규모 기업부터 중견 기업까지 다양한 예산에 맞춘 솔루션을 제안드립니다. 정확한 견적은 요구사항 분석 후 안내해 드리오니, 먼저 문의해 주시기 바랍니다.',
    q3q:'ISMS 인증 준비는 얼마나 걸리나요?',
    q3a:'ISMS 인증 취득까지는 기업의 현황에 따라 통상 6개월~1년 정도 소요됩니다. 갭분석, 보안정책 수립, 보안통제 구현, 내부감사, 심사 준비 등의 단계를 거칩니다. 저희 전문 컨설턴트가 전 과정을 밀착 지원하여 최단 기간 내 인증 취득을 도와드립니다.',
    q4q:'홈페이지 구축 후 유지보수 계약이 가능한가요?',
    q4a:'네, 가능합니다. 홈페이지 구축 완료 후 월정액 유지보수 계약을 체결하실 수 있습니다. 정기적인 콘텐츠 업데이트, 보안 패치, 장애 대응, 기능 개선 등을 포함한 맞춤형 유지보수 플랜을 제공합니다.',
    q5q:'소규모 스타트업도 의뢰할 수 있나요?',
    q5a:'물론입니다. 앤트로메타는 스타트업부터 중견 기업까지 규모에 관계없이 서비스를 제공합니다. 예산과 요구사항에 맞는 최적의 솔루션을 제안하며, 작은 프로젝트도 동일한 품질과 열정으로 진행합니다. 부담 없이 문의해 주세요.',
    /* Contact */
    ct_tag:'CONTACT', ct_title:'문의하기',
    ct_desc:'프로젝트에 대해 이야기해 보세요. 빠르고 친절하게 답변드립니다.',
    ct_sub:'지금 바로 상담을 시작하세요', ct_kbtn:'카카오톡으로 문의하기',
    ct_el:'이메일', ct_pl:'전화', ct_ll:'위치', ct_loc:'경기도 파주시',
    /* Footer */
    /* Why */
    why_tag:'차별화 포인트', why_title:'왜 앤트로메타인가?', why_desc:'고객의 성공이 우리의 목표입니다',
    why1_t:'전문 인력', why1_d:'ERP·웹·카탈로그·ISMS·보안·AI 각 분야를 겉핥기로 아는 사람이 아니라, 실제로 프로젝트를 끝까지 끌고 가본 전담 전문가가 기획부터 구축, 인수인계까지 직접 책임지고 담당합니다. 외주를 다시 외주로 넘기는 구조가 아니라서 커뮤니케이션 손실이 없습니다.',
    why2_t:'검증된 신뢰', why2_d:'GS리테일 보안 취약점 점검, LS산전 모의해킹 진단처럼 대기업이 실제로 맡긴 프로젝트부터 병원·의원 다수, 노인복지기관, 프랜차이즈 브랜드까지 — 업종과 규모를 가리지 않고 쌓아온 납품 실적이 곧 신뢰의 근거입니다.',
    why3_t:'신속한 착수', why3_d:'문의 후 오래 기다리게 하지 않습니다. 초기 상담에서 요구사항을 명확히 파악해 빠르게 일정을 확정하고, 일정이 밀리기 쉬운 개발 프로젝트 특성상 납기 준수를 가장 중요한 원칙으로 삼아 진행합니다.',
    why4_t:'지속적 동반자', why4_d:'프로젝트 납품은 관계의 끝이 아니라 시작입니다. 운영 중 발생하는 문의·장애 대응은 물론, 사업이 성장하면서 새로 필요해지는 기능 확장과 업그레이드까지 함께하며 장기적인 파트너십을 이어갑니다.',
    /* Process */
    proc_tag:'PROCESS', proc_title:'프로젝트는 이렇게 진행됩니다',
    proc1_n:'01', proc1_t:'무료 상담', proc1_d:'비즈니스 목표와 요구사항을 정확히 파악하고 프로젝트 방향을 수립합니다.',
    proc2_n:'02', proc2_t:'기획 & 설계', proc2_d:'분석 결과를 바탕으로 최적의 솔루션을 설계하고 견적을 제안합니다.',
    proc3_n:'03', proc3_t:'개발 & 구현', proc3_d:'전담 전문가 팀이 높은 품질 기준으로 개발·구현합니다.',
    proc4_n:'04', proc4_t:'납품 & 사후 지원', proc4_d:'완성도 높은 납품과 지속적인 유지보수·업그레이드를 제공합니다.',
    /* Service features */
    s1b1:'업무 프로세스 분석 및 재설계', s1b2:'모듈별 맞춤 커스터마이징', s1b3:'데이터 마이그레이션 및 연동', s1b4:'직원 교육 및 운영 지원',
    s1b5:'구축 이후 지속적인 유지보수 및 기능 확장 지원',
    s2b1:'기업·병원·기관 전문 구축', s2b2:'반응형·모바일 최적화 디자인', s2b3:'SEO 최적화 및 성능 튜닝', s2b4:'CMS 연동 및 콘텐츠 관리 시스템',
    s2b5:'오픈 이후 콘텐츠 업데이트·운영 지원 지속',
    s3b1:'브랜드 아이덴티티 완벽 반영', s3b2:'카탈로그·브로슈어·리플렛 제작', s3b3:'디지털·인쇄 겸용 파일 제공', s3b4:'다국어 버전 제작 가능',
    s3b5:'전시회·영업 자료로 바로 활용 가능한 포맷 제공',
    s4b1:'현황 갭분석 및 로드맵 수립', s4b2:'보안 정책·지침서 문서화', s4b3:'임직원 정보보안 교육', s4b4:'인증 심사 대응 및 사후 관리',
    s4b5:'인증 이후 사후관리 심사 대응까지 지원',
    s5b1:'웹·앱·서버 전반 보안 취약점 진단', s5b2:'실전 공격 기법 기반 모의해킹 수행', s5b3:'AI 기반 취약점 분석 자동화 적용', s5b4:'대응 방안 포함 종합 보안 리포트 제공',
    s5b5:'정기 재점검 체계 수립 지원',
    /* 로컬 LLM AI 솔루션 */
    s6t:'로컬 LLM AI 솔루션', s6p:'온프레미스 AI · 완전 프라이빗',
    s6d:'ChatGPT 같은 외부 클라우드 AI에 사내 문서나 고객 데이터를 보내고 싶지 않은 기업을 위해, LLM을 사내 서버에 직접 설치·운용하는 온프레미스 AI 환경을 구축합니다. 사내 매뉴얼·계약서·DB를 연동한 RAG(검색증강생성) 시스템으로 "우리 회사 업무를 아는 AI"를 만들고, 필요하면 업종 특화 파인튜닝까지 진행합니다. 인터넷이 끊기거나 외부 서비스 정책이 바뀌어도 흔들리지 않는 완전 폐쇄망 AI로 보안과 생산성을 함께 확보합니다.',
    s6k1:'온프레미스 AI', s6k2:'데이터 보안', s6k3:'맞춤 파인튜닝',
    s6b1:'사내 서버 기반 LLM 구축 및 최적화', s6b2:'사업 도메인 특화 파인튜닝(Fine-tuning)',
    s6b3:'사내 문서·DB 연동 RAG 시스템 구축', s6b4:'완전 폐쇄망 운용 — 데이터 외부 유출 Zero',
    s6b5:'온프레미스 GPU 서버 구축 컨설팅 포함',
    /* 업데이트된 레퍼런스 설명 */
    rc2_t1:'농생명 전문기업', rc2_t2:'기업 홍보 영상', rc2_t3:'촬영·편집',
    rc2_sub:'Video Production · 농생명 전문기업 홍보 영상',
    rc2_desc:'농생명 전문기업 ㈜ 더기반의 브랜드 가치와 스마트팜·농업 자재 분야 기술력을 전달하는 기업 홍보 영상을 기획부터 최종 납품까지 전 과정 담당하였습니다.',
    rc2_l1:'농생명·스마트팜 브랜드 홍보 영상 기획',
    rc3_t1:'스마트팜 전문기업', rc3_t2:'제품 카탈로그', rc3_t3:'기업 홈페이지',
    rc3_sub:'Catalog + Website · 스마트팜 자동제어시스템 전문기업',
    rc3_desc:'스마트팜 자동제어시스템·공조시스템 개발 전문기업 ㈜ 기반테크의 제품 카탈로그와 기업 홈페이지를 동시에 제작·납품하였습니다. 차광제·종자 코팅제·친환경 농업소재 등 스마트팜 전 제품 라인업을 B2B 특화 디자인으로 표현하여 영업 경쟁력을 강화하였습니다.',
    rc3_l1:'스마트팜 제품 전 라인업 카탈로그 기획·제작', rc3_l2:'국내외 바이어 대상 B2B 특화 디자인 적용',
    rc3_l3:'기업 홈페이지 설계·구축 (기술력·성장성 강조)',
    /* New FAQs */
    q6q:'프로젝트 계약은 어떻게 진행되나요?',
    q6a:'요구사항 분석 후 견적서와 계약서를 작성합니다. 일반적으로 계약금 50% · 중도금 30% · 잔금 20% 형태이며, 프로젝트 규모에 따라 협의 가능합니다. 계약서에는 산출물, 일정, 납품 기준이 명확히 명시됩니다.',
    q7q:'지방에 있어도 프로젝트 의뢰가 가능한가요?',
    q7a:'물론입니다. 경기도 파주 기반이지만 화상 회의와 원격 협업 툴을 통해 전국 어디서나 동일한 품질의 서비스를 제공합니다. 필요 시 직접 방문 미팅도 협의 가능합니다.',
    q8q:'진행한 프로젝트 포트폴리오를 볼 수 있나요?',
    q8a:'카카오톡 채널 또는 이메일로 문의 주시면 기밀 계약 범위 내에서 관련 포트폴리오와 레퍼런스를 안내해 드립니다. 업종별 납품 사례를 최대한 상세히 공유드리겠습니다.',
    /* Industries */
    ind_title:'서비스 산업군', ind1:'제조업', ind2:'의료·바이오', ind3:'IT·소프트웨어', ind4:'유통·물류', ind5:'공공·기관', ind6:'스타트업',
    /* Contact extras */
    ct_hrs_title:'운영 시간', ct_hrs:'평일 09:00 – 18:00\n(토·일·공휴일 휴무)',
    ct_resp_title:'응답 시간', ct_resp:'문의 접수 후\n24시간 이내 답변',
    ft_co:'앤트로메타', ft_loc:'경기도 파주시', ft_est:'설립 2022년 4월', ft_r:'All rights reserved.',
    /* Own Services */
    own_tag:'OWN SERVICES', own_title:'앤트로메타가 직접 운영하는 서비스',
    own_desc:'외주 제작을 넘어, 기획부터 개발·운영까지 직접 책임지는 자체 서비스입니다',
    own_cta:'사이트 바로가기 →',
    os1_cat:'자체 서비스 · 비공개 운영', os1_t1:'이커머스 자동화', os1_t2:'멀티 마켓 연동', os1_t3:'무인 운영',
    os1_name:'드랍쉬핑 자동화 플랫폼', os1_sub:'E-commerce Automation · AliExpress → 국내 마켓 무인 자동화',
    os1_desc:'해외 소싱부터 국내 판매까지 전 과정을 자동화한 자체 운영 이커머스 플랫폼입니다. 상품 랭킹 알고리즘으로 소싱 대상을 선별하고, 스마트스토어·11번가·G마켓·옥션·쿠팡 등 국내 주요 마켓플레이스에 자동 등록합니다. 주문 접수부터 발주, 배송 추적, 마진 계산, 가격 최적화, 이상 감지까지 사람 개입 없이 24시간 운영되며, 저희가 직접 겪은 실제 이커머스 운영 경험을 바탕으로 고객사의 이커머스 자동화 프로젝트에도 그대로 적용하고 있습니다.',
    os1_l1:'AliExpress 소싱 → 마진 계산 → 국내 5개 마켓 자동 등록', os1_l2:'주문·발주·배송추적 무인 자동화 파이프라인',
    os1_l3:'가격 최적화·이상 감지·저조 상품 자동 교체', os1_l4:'내부 운영 데이터라 별도 공개 링크 없이 대시보드로 소개',
    os2_cat:'자체 서비스 · 콘텐츠 미디어', os2_t1:'게임 정보 미디어', os2_t2:'자동 수집 파이프라인', os2_t3:'다국어 SEO',
    os2_name:'cinoz.kr — 로블록스 게임 정보', os2_sub:'Gaming Content Media · 로블록스 인기 게임 코드·정보 사이트',
    os2_desc:'로블록스 인기 게임의 최신 코드와 정보를 한국어·영어·일본어 3개 언어로 제공하는 콘텐츠 미디어 서비스입니다. 매시간 자동으로 실행되는 수집 파이프라인이 신규 게임 발굴, 코드 갱신, 썸네일·장르 정보 보강까지 자동으로 처리하며, 광고 수익화 모델을 자체적으로 설계·운영하고 있습니다.',
    os2_l1:'한·영·일 3개 언어 지원, 200개 이상 게임 정보 제공', os2_l2:'매시간 자동 수집·갱신되는 게임·코드 데이터 파이프라인',
    os2_l3:'SEO 최적화 및 광고 수익화(애드센스) 자체 운영',
    os3_cat:'자체 서비스 · 공공데이터 플랫폼', os3_t1:'공공데이터 분석', os3_t2:'지역 상권 발굴', os3_t3:'자체 알고리즘',
    os3_name:'PinLocal — 로컬 시크릿 발굴 플랫폼', os3_sub:'Public-Data Platform · 지역 상권 데이터 분석 서비스',
    os3_desc:'여행자에게는 덜 알려졌지만 실제로는 이웃들이 즐겨 찾는 동네 상권("로컬 시크릿")을 발굴하는 공공데이터 기반 플랫폼입니다. 관광·상권·인허가 등 여러 공공데이터를 교차분석하는 자체 개발 알고리즘으로 다양성·밀집도·영업지속성·유입지수를 계산해 숨은 동네를 점수화하고, 지도 기반으로 추천 코스까지 자동 생성합니다.',
    os3_l1:'공공데이터 다중 교차분석 기반 자체 발굴 알고리즘', os3_l2:'지역별 추천 코스 자동 생성 및 지도 시각화',
    os3_l3:'전국 단위 확장 중인 데이터 자동 수집 배치 시스템',
    os4_cat:'자체 서비스 · 버티컬 정보 플랫폼', os4_t1:'정비 정보 DB', os4_t2:'정비사 포트폴리오', os4_t3:'커뮤니티',
    os4_name:'MechanicHub — 자동차 정비 정보 플랫폼', os4_sub:'Vertical Information Platform · 정비사 실제 작업기록 기반 DB',
    os4_desc:'정비사가 직접 기록한 실제 수리 사례와 400개 이상의 고장코드 데이터베이스를 기반으로 한 자동차 정비 정보 플랫폼입니다. 차종·세대·트림별 정비 규격, 고장코드별 실제 수리 사례 연결, 정비사 포트폴리오와 정비소 대시보드, Q&A 커뮤니티까지 하나의 서비스 안에서 통합 제공합니다.',
    os4_l1:'실제 정비 사례 2,600건 이상 · 고장코드 400여 개 DB', os4_l2:'차종별 정기 점검 규격 + 고장코드 연계 수리 사례 제공',
    os4_l3:'정비사 포트폴리오·정비소 대시보드·Q&A 커뮤니티 통합'
  },
  en:{
    nav_home:'Home', nav_about:'About', nav_services:'Services', nav_clients:'Clients', nav_blog:'Blog', nav_qa:'Q&A', nav_contact:'Contact', nav_quote:'Get Quote', sc_cta:'Inquire about this service →',
    ab_tag:'ABOUT US', ab_title:'About AnthroMeta', ab_sub:'The IT solutions company designing tomorrow\'s business through technology',
    ab_mv_tag:'MISSION & VISION', ab_mv_title:'Mission & Vision',
    ab_mission_h:'🎯 Mission', ab_mission_p:'We provide practical and sustainable IT solutions to help small and mid-sized enterprises achieve digital transformation and build stronger competitiveness.',
    ab_vision_h:'🔭 Vision', ab_vision_p:'We aim to become the most trusted IT partner in every company\'s digital journey, driving smart innovation across industries with AI and data-driven solutions.',
    ab_info_tag:'COMPANY', ab_info_title:'Company Info',
    ab_intro:'AnthroMeta is an IT solutions company founded in Paju, Gyeonggi-do in April 2022. From ERP implementation to website development, ISMS consulting, vulnerability assessment & penetration testing, and local LLM deployment, we support every stage of enterprise digital transformation.',
    ab_intro2:'Backed by real-world references across manufacturing, distribution, and security — including GS Retail, LS Electric, Giban Tech, and Woo Young Tech — we deliver IT solutions optimized for each industry, quickly and accurately.',
    ab_tl_tag:'HISTORY', ab_tl_title:'Our History', ab_tl_sub:'The growth journey of AnthroMeta',
    tl1_t:'AnthroMeta Founded', tl1_d:'Established in Paju, Gyeonggi-do as an IT solutions firm. Launched ERP and website development services.',
    tl2_t:'GS Retail Security Assessment', tl2_d:'Performed a security vulnerability assessment program for a major retail enterprise. First large-scale reference secured.',
    tl3_t:'Manufacturing References Expanded', tl3_d:'Secured multiple references in manufacturing/IT sectors including Giban Tech (smart farm) and Woo Young Tech (multilingual site).',
    tl4_t:'ISMS Consulting Service Launched', tl4_d:'Recruited information security specialists and officially launched ISMS/ISMS-P certification consulting service.',
    tl5_t:'Multiple Medical Websites Delivered', tl5_d:'Completed healthcare-specific website solutions for hospitals, clinics, and medical offices. Contract signed with Korean Neurological Association.',
    tl6_t:'Local LLM AI Solution Launched', tl6_d:'Launched on-premises LLM deployment service. AI solutions provided for enterprises where data security is critical.',
    tl7_t:'Continuing to Grow', tl7_d:'Expanding ERP/AI/LLM integrated solutions and building new partnerships. Supporting digital transformation for more enterprises.',
    ab_val_tag:'CORE VALUES', ab_val_title:'Core Values', ab_val_sub:'The AnthroMeta way of working',
    val1_t:'Speed', val1_p:'We support clients with fast delivery and immediate communication so no business opportunity is missed.',
    val2_t:'Expertise', val2_p:'Specialists in each field guarantee the highest quality from planning through implementation and operation.',
    val3_t:'Reliability', val3_p:'Our 100% project completion principle and transparent communication build long-term partnerships with clients.',
    val4_t:'Innovation', val4_p:'We rapidly apply the latest technologies — AI, LLM, and more — to create competitive advantage for our clients.',
    blog_tag:'INSIGHT & BLOG', blog_title:'IT Insights', blog_sub:'Latest trends and practical know-how in AI · ERP · Web development · Security',
    cat_all:'All', cat_ai:'AI · LLM', cat_web:'Web Dev', cat_erp:'ERP', cat_sec:'Security',
    qt_tag:'QUOTE REQUEST', qt_title:'Request a Quote', qt_sub:'Submit your project details and we\'ll provide a custom quote within 24 hours',
    qt_proc_t:'🗓️ Quote Process', qt_s1:'Fill out & submit the form', qt_s2:'Our team contacts you within 24h', qt_s3:'Detailed requirements meeting (online/offline)', qt_s4:'Custom quote sent', qt_s5:'Contract & project kickoff',
    qt_tip_t:'💡 This is for you if...', qt_tip_p:'You need a website, ERP, or AI solution but don\'t know where to start. You want to estimate the budget first. You\'re comparing multiple vendors. All are welcome — no pressure.',
    qt_contact_t:'📧 Quick Contact', qt_contact_p:'Feel free to reach out directly by email instead of the form.',
    qt_f_svc:'Select Services (multiple OK)', qt_f_basic:'Basic Information', qt_f_project:'Project Information',
    qt_f_company:'Company Name', qt_f_name:'Contact Person', qt_f_email:'Email', qt_f_phone:'Phone (optional)',
    qt_f_budget:'Budget Range', qt_bud0:'Please select', qt_bud1:'Under ₩5M', qt_bud2:'₩5M ~ ₩10M', qt_bud3:'₩10M ~ ₩30M', qt_bud4:'₩30M+', qt_bud5:'TBD / Negotiable',
    qt_f_schedule:'Target Completion', qt_sch0:'Please select', qt_sch1:'Within 1 month', qt_sch2:'1 ~ 3 months', qt_sch3:'3 ~ 6 months', qt_sch4:'6+ months', qt_sch5:'TBD / Negotiable',
    qt_f_desc:'Project Description', qt_agree:'I agree to the collection and use of personal information. Data will only be used for quote purposes and will not be shared with third parties. <a href="privacy.html" style="color:var(--teal);text-decoration:underline" target="_blank">Privacy Policy</a>',
    qt_submit:'Send Quote Request', qt_ok_t:'Quote Request Received!', qt_ok_p:'Our team will contact you within 24 hours.', qt_ok_btn:'Back to Home',
    hero_badge:'IT Solution Specialist · Paju, Gyeonggi',
    hero_title:"Designing Tomorrow's<br>Business with Technology",
    hero_sub:'ERP · Web · ISMS · AI · Local LLM Specialist',
    hero_cta1:'View Services', hero_cta2:'Contact Us', hero_scroll:'SCROLL',
    about_tag:'About Us', about_title:'Building the Future with Technology',
    about_desc:'Since our founding in 2022 in Paju, Gyeonggi, AnthroMeta has grown alongside clients of every size and industry — from large enterprises to small businesses, hospitals, and public institutions. From hands-on projects like ERP builds, website development, and catalog design to ISMS certification consulting, vulnerability assessment and penetration testing, and local LLM-based AI solutions — one team takes full responsibility for solving your digital transformation challenges, from planning through deployment and operation. Our principle isn\'t "deliver and disappear" — it\'s staying on as a partner long after launch.',
    about_lb1:'Founded', about_lv1:'April 2022',
    about_lb2:'Location', about_lv2:'Paju, Gyeonggi',
    about_lb3:'Industry', about_lv3:'IT Solutions',
    st1l:'Founded', st2l:'Projects Done', st3l:'Service Areas', st4l:'Satisfaction',
    svc_prev_tag:'SERVICES', svc_prev_title:'Our Services',
    svc_prev_desc:'Tailored solutions for your digital transformation',
    svc_link:'View All Services →',
    s1t:'ERP Solutions', s1p:'Custom ERP Build & Operations',
    s2t:'Website Development', s2p:'Corp · Hospital · Institution',
    s3t:'Catalog Design', s3p:'Brand Promotional Materials',
    s4t:'ISMS Consulting', s4p:'Information Security Certification',
    s5t:'Vulnerability Assessment & Pentesting', s5p:'AI-Powered Analysis · Real-World Attack Scenarios',
    svc_tag:'SERVICES', svc_title:'Our Services',
    svc_desc:'Tailored solutions to accelerate your digital transformation',
    s1d:'We build custom ERP systems that reflect how your business actually works — not what a generic package assumes. Core modules like inventory, accounting, HR, and production are selected and designed only where you need them, migrating existing spreadsheet- and paper-based workflows into the system with minimal disruption. Support continues after go-live with on-site training and issue response, so the ERP gets used — not shelved.',
    s1k1:'Custom Build', s1k2:'Process Optimization', s1k3:'Ongoing Support',
    s2d:'From corporate sites to hospital booking integration and public-institution accessibility compliance, we design each website around its actual purpose from the planning stage. Every project includes a responsive layout that holds up across mobile, tablet, and desktop, plus the SEO fundamentals needed to actually surface in Naver and Google search. Support continues after launch with content updates and ongoing maintenance, so the site doesn\'t just sit there once it\'s built.',
    s2k1:'Corp / Hospital', s2k2:'Responsive', s2k3:'SEO',
    s3d:'We design the story structure first — so anyone seeing your product or service for the first time immediately gets what makes it stand out — then produce it as a catalog, brochure, or leaflet. High-resolution CMYK files for print and digital files for online use are delivered together, ready for trade shows, sales meetings, or your website. Multilingual versions are also available for companies working with overseas buyers.',
    s3k1:'Branding', s3k2:'Print', s3k3:'Brochure',
    s4d:'For companies pursuing ISMS certification for the first time, we start with a gap analysis of your current security posture — so you\'re never guessing what to do first. We support the full certification process: building security policies and guidelines, training staff, and preparing for the certification audit, then continue with post-certification audit support. The goal isn\'t paperwork for compliance — it\'s a security system that actually works.',
    s4k1:'Gap Analysis', s4k2:'Certification', s4k3:'Security Policy',
    s5d:'We test web, app, and server environments using the same penetration techniques real attackers use. AI-powered automated analysis scans broad surfaces quickly, while our team manually designs and executes real-world attack scenarios on anything flagged. Rather than stopping at diagnosis, we deliver a report with risk-ranked priorities and concrete remediation steps, so you know exactly what to fix first.',
    s5k1:'Vulnerability Assessment', s5k2:'Penetration Testing', s5k3:'Security Consulting',
    cl_strip_tag:'CLIENTS', cl_strip_title:'Our Clients',
    cl_link:'View All Clients →',
    cl_tag:'CLIENTS', cl_title:'Our Clients',
    cl_desc:'Growing alongside companies across diverse industries',
    cl_hosp:'Medical / Hospitals', cl_neuro:'Korean Neurology Assoc.',
    cl_hosp_name:'Medical Institutions',
    cb_svc1:'Security Assessment', cb_svc2:'Video Production', cb_svc3:'Smart Farm Catalog+Site',
    cb_svc4:'Multi-lang Site · ERP', cb_svc5:'Catalog · IT MOU', cb_svc6:'Website', cb_svc7:'Website (Soon)',
    cb_svc8:'Penetration Testing', cb_svc9:'Website', cb_svc10:'Franchise Website',
    cl_trust:"AnthroMeta has built trust with leading companies including GS Retail, LS Electric, The Giban, Giban Tech, Wooyoung Tech, But&But, and Bao Beer, as well as numerous medical institutions. We deliver excellence regardless of industry or scale.",
    ref_tag:'REFERENCES', ref_title:'Project References', ref_desc:'Highlights from our delivered projects',
    rc1_cat:'Security Assessment', rc1_t1:'Retail Enterprise', rc1_t2:'Vulnerability Assessment', rc1_t3:'Security Consulting',
    rc1_sub:'Security Assessment · Vulnerability Assessment Program',
    rc1_desc:'We performed a security vulnerability assessment program covering the IT infrastructure and services of GS Retail, a major domestic retail enterprise. Systematic diagnostics were conducted across web, app, and server environments, with detailed findings reports and prioritized remediation guidance to strengthen overall information security posture.',
    rc1_l1:'Security vulnerability diagnostics across web, app & server', rc1_l2:'Risk-rated findings with remediation guidance',
    rc1_l3:'Detailed assessment report delivery', rc1_l4:'Support for establishing periodic assessment cycles',
    rc2_cat:'Video Production', rc2_t1:'Corporate Promo', rc2_t2:'Filming & Editing', rc2_t3:'Motion Graphics',
    rc2_sub:'Video Production · Corporate Promotional Video',
    rc2_desc:"We handled the full production of The Giban's corporate promotional video — from storyboarding and on-site filming to professional editing with motion graphics, subtitles, and BGM.",
    rc2_l1:'Storyboard planning for corporate promo', rc2_l2:'On-site filming with professional equipment',
    rc2_l3:'Motion graphics, subtitles & BGM editing', rc2_l4:'Multi-format delivery: YouTube, SNS, PPT',
    rc3_cat:'Catalog + Website', rc3_t1:'Product Catalog', rc3_t2:'Corporate Site', rc3_t3:'B2B',
    rc3_sub:'Catalog Design + Website · Tech & Manufacturing Firm',
    rc3_desc:'We simultaneously delivered a product catalog and corporate website for Giban Tech, a manufacturing and IT specialist. B2B-focused design effectively communicates technical specs and product strengths.',
    rc3_l1:'Full product lineup catalog planning & production', rc3_l2:'B2B sales-optimized design & layout',
    rc3_l3:'Corporate website design & build', rc3_l4:'High-res files for both digital and print',
    rc4_cat:'Multilingual Site + Catalog', rc4_t1:'Multilingual Site', rc4_t2:'Catalog', rc4_t3:'ERP Upcoming',
    rc4_ongoing:'ERP In Progress',
    rc4_sub:'Multilingual Website + Catalog · ERP Implementation Upcoming',
    rc4_desc:'We built a trilingual (KO/EN/JP) website and English catalog for Wooyoung Tech targeting global markets. ERP implementation consulting is now underway for the next phase of digital transformation.',
    rc4_l1:'Trilingual website (KO/EN/JP) development', rc4_l2:'English product catalog for overseas buyers',
    rc4_l3:'Global SEO & international search visibility', rc4_l4:'Custom ERP implementation consulting (ongoing)',
    rc5_cat:'Catalog + IT MOU', rc5_t1:'Brand Catalog', rc5_t2:'Brochure', rc5_t3:'IT MOU',
    rc5_ongoing:'MOU Partner',
    rc5_sub:'Catalog Design · IT Consulting MOU · Strategic IT Partnership',
    rc5_desc:"We produced a comprehensive brand catalog for But&But and subsequently signed an MOU for IT consulting services, establishing a long-term strategic partnership for their digital transformation.",
    rc5_l1:'Full brand catalog planning & production', rc5_l2:'CMYK print + RGB digital dual delivery',
    rc5_l3:'IT Consulting MOU — strategic partnership', rc5_l4:'Joint digital transformation roadmap',
    rc6_cat:'Medical Website', rc6_t1:'Clinics & Hospitals', rc6_t2:'Booking Integration', rc6_t3:'Mobile-first',
    rc6_name:'Multiple Medical Clients',
    rc6_sub:'Medical Website · Clinics, Hospitals & Healthcare Providers',
    rc6_desc:'We have delivered websites for numerous medical providers across specialties — internal medicine, dermatology, dental, and traditional medicine — with patient-centric UX and online booking integration.',
    rc6_l1:'Patient-centered UX medical website builds', rc6_l2:'Specialty, staff & facility content pages',
    rc6_l3:'Online appointment booking integration', rc6_l4:'Healthcare law compliance & privacy design',
    rc7_cat:'Association Website', rc7_t1:'Medical Association', rc7_t2:'Institutional Site', rc7_t3:'Upcoming',
    rc7_ongoing:'In Preparation',
    rc7_name:'Korean Neurological Assoc.',
    rc7_sub:'Medical Association Website · Official site for a National Medical Body',
    rc7_desc:'We are preparing the official website for the Korean Neurological Association, representing neurology specialists nationwide. The site will integrate member management, academic resources, and conference schedules.',
    rc7_l1:'Official site for national neurology specialist body', rc7_l2:'Integrated member, academic & event platform',
    rc7_l3:'Dual UX for specialists & general public', rc7_l4:'Accessibility compliance + multilingual support',
    rc8_cat:'Penetration Testing', rc8_t1:'Electrical Equipment Manufacturer', rc8_t2:'Penetration Testing', rc8_t3:'Breach Scenario Analysis',
    rc8_sub:'Penetration Testing · Security Assessment',
    rc8_desc:'We performed penetration testing using real-world attack techniques against LS Electric, a specialist in electrical and power equipment. Security vulnerabilities were validated through practical breach scenarios — external intrusion, internal privilege escalation, and access to critical systems — with a comprehensive assessment report including remediation guidance.',
    rc8_l1:'Penetration testing using real-world attack techniques', rc8_l2:'External intrusion & privilege escalation scenario validation',
    rc8_l3:'Critical system access analysis', rc8_l4:'Comprehensive assessment report with remediation guidance',
    rc9_cat:'Website Dev.', rc9_t1:'Senior Welfare Institution', rc9_t2:'Institutional Site', rc9_t3:'Accessible Design',
    rc9_sub:'Institutional Website · Senior Welfare Center Official Site',
    rc9_desc:'We planned, designed, and built the official website for Goyang Senior Club. Accessibility-focused UI — large text and high-contrast colors — makes the site easy to use for seniors and caregivers alike, with intuitive content covering programs, notices, and facility information.',
    rc9_l1:'Accessibility-focused UI/UX for senior welfare institutions', rc9_l2:'Program & notice content organization',
    rc9_l3:'Mobile-optimized responsive design', rc9_l4:'Improved usability for local community members',
    rc10_cat:'Franchise Website', rc10_t1:'F&B Franchise', rc10_t2:'Franchisee Info', rc10_t3:'Brand Website',
    rc10_sub:'Franchise Website · Franchise Brand Website Build',
    rc10_desc:'We planned, designed, and built the official website for Bao Beer, an F&B franchise brand. The site features brand story, menu, and store locator content alongside a franchise inquiry function to support new franchisee acquisition, with consistent brand tone and visual identity to build customer trust.',
    rc10_l1:'Brand story, menu & store locator content', rc10_l2:'Franchise inquiry feature to support new franchisee acquisition',
    rc10_l3:'Visual design aligned with brand tone', rc10_l4:'Mobile-optimized responsive design',
    ind_h:'Expertise Across Industries',
    cta_title:'Ready to Start Your Project?',
    cta_desc:"Contact us without hesitation. We'll respond quickly and with care.",
    cta_btn:'Contact Us Now',
    qa_tag:'FAQ', qa_title:'Frequently Asked Questions', qa_desc:'Find answers to common questions',
    q1q:'How long does website development take?',
    q1a:'A typical corporate website takes approximately 4–8 weeks including planning, design, and development. Timeline varies by scope — hospitals or large institutions may need additional time. We provide an accurate schedule after the initial consultation.',
    q2q:'How much does ERP implementation cost?',
    q2a:'Costs vary significantly by company size, number of modules, and customization scope. We offer solutions for a wide range of budgets. Contact us for a precise quote after requirements analysis.',
    q3q:'How long does ISMS certification preparation take?',
    q3a:'Certification typically takes 6 months to 1 year depending on current state. Steps include gap analysis, policy development, control implementation, internal audits, and audit preparation. Our consultants provide hands-on support throughout.',
    q4q:'Can we sign a maintenance contract after launch?',
    q4a:'Yes. You can enter a monthly maintenance contract after launch covering content updates, security patches, incident response, and feature improvements — all in a plan customized to your needs.',
    q5q:'Can small startups request services?',
    q5a:"Of course. AnthroMeta serves companies of all sizes. We propose solutions that fit your budget and bring the same quality and commitment to every project. Don't hesitate to reach out.",
    ct_tag:'CONTACT', ct_title:'Contact Us',
    ct_desc:"Let's talk about your project. We respond quickly and with care.",
    ct_sub:'Start your consultation today', ct_kbtn:'Contact via KakaoTalk',
    ct_el:'Email', ct_pl:'Phone', ct_ll:'Location', ct_loc:'Paju, Gyeonggi, Korea',
    why_tag:'Why Choose Us', why_title:'Why AnthroMeta?', why_desc:'Your success is our commitment',
    why1_t:'Deep Expertise', why1_d:'Our specialists don\'t have surface-level knowledge across ERP, web, catalog, ISMS, security, and AI — they\'ve personally carried real projects from planning through build-out and handoff. Nothing gets outsourced to a second layer of subcontractors, so nothing gets lost in translation.',
    why2_t:'Proven Track Record', why2_d:'From enterprise-level work like GS Retail\'s security vulnerability assessment and LS Electric\'s penetration testing, to numerous hospitals and clinics, a senior welfare center, and franchise brands — our track record spans every industry and scale, and that\'s exactly where our credibility comes from.',
    why3_t:'Fast Start', why3_d:'We don\'t keep you waiting after you reach out. We nail down requirements clearly in the initial consultation and lock in a schedule fast — and because development projects are especially prone to slipping, we treat deadline adherence as our top priority.',
    why4_t:'Long-term Partner', why4_d:'Delivery isn\'t the end of the relationship — it\'s the beginning. We handle ongoing questions and issue response, and as your business grows and needs new features or upgrades, we stay on as a long-term partner.',
    proc_tag:'PROCESS', proc_title:'How We Work',
    proc1_n:'01', proc1_t:'Free Consultation', proc1_d:'We analyze your business goals and requirements to define the project direction.',
    proc2_n:'02', proc2_t:'Planning & Design', proc2_d:'We design the optimal solution and present a detailed proposal and quote.',
    proc3_n:'03', proc3_t:'Development', proc3_d:'Our dedicated expert team builds with precision and high quality standards.',
    proc4_n:'04', proc4_t:'Delivery & Support', proc4_d:'High-quality delivery followed by continuous maintenance and upgrades.',
    s1b1:'Business process analysis & redesign', s1b2:'Module-level customization', s1b3:'Data migration & system integration', s1b4:'Staff training & operations support',
    s1b5:'Ongoing maintenance & feature expansion after go-live',
    s2b1:'Corp / hospital / institution expertise', s2b2:'Responsive & mobile-optimized design', s2b3:'SEO optimization & performance tuning', s2b4:'CMS integration & content management',
    s2b5:'Post-launch content updates & operational support',
    s3b1:'Full brand identity alignment', s3b2:'Catalogs, brochures & leaflets', s3b3:'Digital & print dual-format files', s3b4:'Multilingual versions available',
    s3b5:'Ready-to-use formats for trade shows & sales materials',
    s4b1:'Gap analysis & roadmap planning', s4b2:'Security policy documentation', s4b3:'Employee information security training', s4b4:'Audit preparation & post-cert management',
    s4b5:'Post-certification audit support',
    s5b1:'Security vulnerability diagnostics across web, app & server', s5b2:'Penetration testing using real-world attack techniques', s5b3:'AI-powered automated vulnerability analysis', s5b4:'Comprehensive security report with remediation guidance',
    s5b5:'Recurring re-assessment program setup',
    s6t:'Local LLM AI Solutions', s6p:'On-Premise AI · Fully Private',
    s6d:'For companies that don\'t want internal documents or customer data sent to external cloud AI services like ChatGPT, we deploy and operate LLMs directly on your own servers as a fully on-premise AI environment. We build a RAG (retrieval-augmented generation) system connected to your internal manuals, contracts, and databases — creating an AI that actually knows how your company works — with industry-specific fine-tuning available where needed. A fully air-gapped AI that keeps working even if the internet goes down or an external vendor changes its policy, delivering security and productivity together.',
    s6k1:'On-Premise AI', s6k2:'Data Security', s6k3:'Custom Fine-tuning',
    s6b1:'On-site LLM deployment & GPU optimization', s6b2:'Domain-specific fine-tuning for your business',
    s6b3:'RAG system with internal docs & database', s6b4:'Air-gapped operation — zero data leakage',
    s6b5:'On-premise GPU server build consulting included',
    ind_h:'Expertise Across Industries',
    q6q:'How does the contract process work?',
    q6a:'After requirements analysis, we prepare a quote and contract. Payment is typically 50% upfront, 30% mid-project, and 20% on delivery — adjustable based on scope. Deliverables, timeline, and acceptance criteria are clearly defined in the contract.',
    q7q:'Can companies outside the Seoul metro area request services?',
    q7a:'Absolutely. While based in Paju, Gyeonggi, we serve clients nationwide via video conferencing and remote collaboration tools, delivering the same quality as in-person. On-site visits can also be arranged if needed.',
    q8q:'Can I see your portfolio or client references?',
    q8a:"Please reach out via KakaoTalk or email. We'll share relevant portfolio pieces and references within the bounds of any confidentiality agreements — as detailed as possible, categorized by industry.",
    ind_title:'Industries We Serve', ind1:'Manufacturing', ind2:'Healthcare', ind3:'IT / Software', ind4:'Distribution', ind5:'Public / Institution', ind6:'Startup',
    ct_hrs_title:'Business Hours', ct_hrs:'Mon – Fri  09:00 – 18:00\n(Closed weekends & holidays)',
    ct_resp_title:'Response Time', ct_resp:'Within 24 hours\nof business day inquiry',
    ft_co:'AnthroMeta', ft_loc:'Paju, Gyeonggi', ft_est:'Est. April 2022', ft_r:'All rights reserved.',
    /* Own Services */
    own_tag:'OWN SERVICES', own_title:'Services We Build and Run Ourselves',
    own_desc:"Beyond client work, these are our own products — we own the full cycle from planning to development and operations",
    own_cta:'Visit site →',
    os1_cat:'In-house · Private operation', os1_t1:'E-commerce Automation', os1_t2:'Multi-Marketplace', os1_t3:'Unmanned Operation',
    os1_name:'Dropshipping Automation Platform', os1_sub:'E-commerce Automation · AliExpress → Korean Marketplaces, Fully Automated',
    os1_desc:"An e-commerce platform we built and operate ourselves, automating the entire flow from overseas sourcing to domestic sales. A ranking algorithm selects sourcing candidates, then auto-lists them on Korea's major marketplaces — Smartstore, 11st, Gmarket/Auction, and Coupang. Order intake, purchasing, shipment tracking, margin calculation, price optimization, and anomaly detection all run 24/7 without human intervention. The operational lessons from running this ourselves feed directly into the e-commerce automation projects we build for clients.",
    os1_l1:'AliExpress sourcing → margin calc → auto-listing on 5 Korean marketplaces', os1_l2:'Unmanned pipeline for orders, purchasing, and shipment tracking',
    os1_l3:'Automated price optimization, anomaly detection, and slow-mover replacement', os1_l4:'Internal operations tool — shown here via dashboard rather than a public link',
    os2_cat:'In-house · Content media', os2_t1:'Gaming Content Media', os2_t2:'Automated Collection Pipeline', os2_t3:'Multilingual SEO',
    os2_name:'cinoz.kr — Roblox Game Info', os2_sub:'Gaming Content Media · Roblox Game Codes & Info Site',
    os2_desc:'A content media service providing the latest codes and info for popular Roblox games in Korean, English, and Japanese. An hourly automated pipeline handles new-game discovery, code updates, and thumbnail/genre enrichment, with an ad-based monetization model we designed and run ourselves.',
    os2_l1:'Korean/English/Japanese support, 200+ games covered', os2_l2:'Hourly automated pipeline for game and code data',
    os2_l3:'Self-managed SEO optimization and AdSense monetization',
    os3_cat:'In-house · Public-data platform', os3_t1:'Public-Data Analysis', os3_t2:'Local Commercial Discovery', os3_t3:'Proprietary Algorithm',
    os3_name:'PinLocal — Local Secret Discovery Platform', os3_sub:'Public-Data Platform · Local Commercial-Area Analysis Service',
    os3_desc:"A public-data-driven platform that surfaces neighborhood commercial areas (\"local secrets\") that get little tourist traffic but are genuinely loved by locals. A proprietary algorithm cross-analyzes tourism, commercial, and licensing data to score diversity, density, business longevity, and inflow index — surfacing hidden neighborhoods and auto-generating recommended routes on a map.",
    os3_l1:'Proprietary discovery algorithm from cross-analyzing multiple public datasets', os3_l2:'Auto-generated recommended routes with map visualization',
    os3_l3:'Automated data-collection batch system, currently expanding nationwide',
    os4_cat:'In-house · Vertical information platform', os4_t1:'Repair Info Database', os4_t2:'Mechanic Portfolios', os4_t3:'Community',
    os4_name:'MechanicHub — Auto Repair Information Platform', os4_sub:'Vertical Information Platform · Database Built on Real Mechanic Work Records',
    os4_desc:'An auto repair information platform built on real repair cases logged directly by mechanics and a database of 400+ fault codes. It brings together maintenance specs by make/generation/trim, real repair cases linked to fault codes, mechanic portfolios and shop dashboards, and a Q&A community — all in one service.',
    os4_l1:'2,600+ real repair cases · 400+ fault codes in the database', os4_l2:'Maintenance specs by vehicle plus fault-code-linked repair cases',
    os4_l3:'Mechanic portfolios, shop dashboards, and Q&A community, all integrated'
  },
  ja:{
    nav_home:'ホーム', nav_about:'会社紹介', nav_services:'サービス', nav_clients:'取引先', nav_blog:'ブログ', nav_qa:'Q&A', nav_contact:'お問い合わせ', nav_quote:'見積依頼', sc_cta:'このサービスへお問い合わせ →',
    ab_tag:'ABOUT US', ab_title:'アンスロメタ紹介', ab_sub:'技術でビジネスの明日を設計するITソリューション専門企業',
    ab_mv_tag:'MISSION & VISION', ab_mv_title:'ミッションとビジョン',
    ab_mission_h:'🎯 ミッション', ab_mission_p:'中小・中堅企業が最新のIT技術によりデジタル変革を実現し、より高い競争力を身につけられるよう、実践的で持続可能なソリューションを提供します。',
    ab_vision_h:'🔭 ビジョン', ab_vision_p:'企業のデジタルトランスフォーメーションの旅で最も信頼されるITパートナーとして、AIとデータ駆動型ソリューションで産業全般のスマートイノベーションを牽引します。',
    ab_info_tag:'COMPANY', ab_info_title:'会社情報',
    ab_intro:'アンスロメタは2022年4月、韓国・京畿道坡州市に設立されたITソリューション専門企業です。ERP構築からウェブサイト制作、ISMSコンサルティング、脆弱性診断・模擬ハッキング、ローカルLLM構築まで、企業のデジタル変革を一貫してサポートします。',
    ab_intro2:'GSリテール、LS産電、ギバンテク、ウヨンテクなど製造・流通・セキュリティ分野の豊富なリファレンスを持ち、各業種に最適化されたITソリューションを迅速かつ正確に提供します。',
    ab_tl_tag:'HISTORY', ab_tl_title:'沿革', ab_tl_sub:'アンスロメタの成長の歩み',
    tl1_t:'アンスロメタ設立', tl1_d:'京畿道坡州市にてITソリューション専門企業として創業。ERPおよびウェブサイト制作事業を開始。',
    tl2_t:'GSリテール セキュリティ脆弱性診断', tl2_d:'大手流通企業向けセキュリティ脆弱性診断プログラムを実施。初の大型リファレンスを獲得。',
    tl3_t:'製造業リファレンス拡大', tl3_d:'ギバンテク（スマートファーム）、ウヨンテク（多言語サイト）など製造・IT分野のリファレンスを多数獲得。',
    tl4_t:'ISMSコンサルティングサービス開始', tl4_d:'情報セキュリティ専門人材を採用し、ISMS・ISMS-P認証コンサルティングサービスを正式ローンチ。',
    tl5_t:'医療機関ウェブサイト多数納品', tl5_d:'病院・クリニック特化のウェブサイトソリューションを完成。大韓神経科協会と契約締結。',
    tl6_t:'ローカルLLM AIソリューション開始', tl6_d:'オンプレミス大規模言語モデル（LLM）構築サービスを開始。データセキュリティ重視企業向けAIソリューションを提供。',
    tl7_t:'継続成長中', tl7_d:'ERP・AI・LLM統合ソリューションを拡張し、新規パートナーシップを構築。より多くの企業のデジタル変革を支援します。',
    ab_val_tag:'CORE VALUES', ab_val_title:'コアバリュー', ab_val_sub:'アンスロメタの仕事の流儀',
    val1_t:'迅速性', val1_p:'迅速な納期と即時コミュニケーションで、ビジネスチャンスを逃さないようサポートします。',
    val2_t:'専門性', val2_p:'各分野の専門人材が企画から構築、運営まで最高水準の品質を保証します。',
    val3_t:'信頼性', val3_p:'100%プロジェクト完遂の原則と透明なコミュニケーションで、顧客と長期的なパートナーシップを維持します。',
    val4_t:'革新性', val4_p:'AI・LLMなど最新技術を迅速にビジネスへ適用し、競争優位性を創出します。',
    blog_tag:'INSIGHT & BLOG', blog_title:'ITインサイト', blog_sub:'AI・ERP・ウェブ開発・セキュリティ分野の最新トレンドと実務ノウハウ',
    cat_all:'すべて', cat_ai:'AI・LLM', cat_web:'ウェブ開発', cat_erp:'ERP', cat_sec:'セキュリティ',
    qt_tag:'QUOTE REQUEST', qt_title:'見積依頼', qt_sub:'プロジェクト情報をご入力いただければ、24時間以内にカスタム見積をお届けします',
    qt_proc_t:'🗓️ 見積プロセス', qt_s1:'フォーム記入・送信', qt_s2:'24時間以内に担当者からご連絡', qt_s3:'要件詳細ミーティング（オン/オフ）', qt_s4:'カスタム見積書を送付', qt_s5:'契約・プロジェクト着手',
    qt_tip_t:'💡 こんな方におすすめ', qt_tip_p:'ウェブサイト・ERP・AI導入が必要だが、どこから始めればよいかわからない方。予算を先に把握したい方。複数社の見積を比較したい方。お気軽にお問い合わせください。',
    qt_contact_t:'📧 直接お問い合わせ', qt_contact_p:'フォームの代わりにメールで直接お問い合わせいただいても構いません。',
    qt_f_svc:'サービス選択（複数選択可）', qt_f_basic:'基本情報', qt_f_project:'プロジェクト情報',
    qt_f_company:'会社名', qt_f_name:'担当者名', qt_f_email:'メールアドレス', qt_f_phone:'電話番号（任意）',
    qt_f_budget:'予算規模', qt_bud0:'選択してください', qt_bud1:'500万ウォン以下', qt_bud2:'500〜1,000万ウォン', qt_bud3:'1,000〜3,000万ウォン', qt_bud4:'3,000万ウォン以上', qt_bud5:'未定・協議',
    qt_f_schedule:'希望完了時期', qt_sch0:'選択してください', qt_sch1:'1ヶ月以内', qt_sch2:'1〜3ヶ月', qt_sch3:'3〜6ヶ月', qt_sch4:'6ヶ月以上', qt_sch5:'未定・協議',
    qt_f_desc:'プロジェクト内容', qt_agree:'個人情報の収集・利用に同意します。収集された情報は見積提供目的にのみ使用され、第三者への提供は行いません。 <a href="privacy.html" style="color:var(--teal);text-decoration:underline" target="_blank">プライバシーポリシー</a>',
    qt_submit:'見積依頼を送る', qt_ok_t:'見積依頼を受け付けました！', qt_ok_p:'24時間以内に担当者よりご連絡いたします。', qt_ok_btn:'ホームに戻る',
    hero_badge:'ITソリューション専門企業 · 京畿道坡州市',
    hero_title:'テクノロジーでビジネスの<br>未来を設計します',
    hero_sub:'ERP・ウェブ・ISMS・AI・ローカルLLMソリューション専門企業',
    hero_cta1:'サービスを見る', hero_cta2:'お問い合わせ', hero_scroll:'SCROLL',
    about_tag:'会社紹介', about_title:'テクノロジーで未来を切り拓く企業',
    about_desc:'アンスロメタは2022年に京畿道坡州市で設立して以来、大企業から中小企業、病院、公共機関まで、規模や業種を問わない多様な顧客とともに成長してきたITソリューション専門企業です。ERP構築、ウェブサイト制作、カタログデザインといった実務型プロジェクトから、ISMS認証コンサルティング、脆弱性診断・模擬ハッキング、ローカルLLM活用のAIソリューションまで——企業がデジタル変革で直面する課題を、企画から構築、運用まで一つのチームが責任を持って解決します。「作って終わり」ではなく、納品後も伴走し続けるパートナーであることを原則としています。',
    about_lb1:'設立', about_lv1:'2022年4月',
    about_lb2:'所在地', about_lv2:'京畿道坡州市',
    about_lb3:'業種', about_lv3:'ITソリューション',
    st1l:'設立年', st2l:'完了PJ', st3l:'専門サービス', st4l:'顧客満足',
    svc_prev_tag:'サービス', svc_prev_title:'主要サービス',
    svc_prev_desc:'デジタルトランスフォーメーションを実現するソリューション',
    svc_link:'すべてのサービスを見る →',
    s1t:'ERPソリューション', s1p:'企業カスタムERP構築・運用',
    s2t:'ウェブサイト制作', s2p:'企業・病院・公共機関サイト',
    s3t:'カタログデザイン', s3p:'ブランドPR資料の企画・制作',
    s4t:'ISMSコンサルティング', s4p:'情報セキュリティ認証支援',
    s5t:'脆弱性診断・模擬ハッキング', s5p:'AI活用診断 · 実践的侵害シナリオ',
    svc_tag:'サービス', svc_title:'主要サービス',
    svc_desc:'企業のデジタルトランスフォーメーションを実現するソリューションを提供します',
    s1d:'既製パッケージでは対応できない、企業固有の業務フローをそのまま反映したカスタムERPを構築します。在庫・会計・人事・生産など必要なモジュールだけを厳選して設計し、これまでExcelや手作業で処理していた業務を最小限の混乱でシステムへ移行します。導入後も現場担当者向け研修や障害対応まで責任を持って支援し、「作って終わり」ではなく実際に使われるERPを実現します。',
    s1k1:'カスタム構築', s1k2:'プロセス最適化', s1k3:'運用サポート',
    s2d:'企業サイトから病院の予約連携、公共機関のアクセシビリティ基準対応まで、目的に応じて企画段階から一緒に設計します。モバイル・タブレット・デスクトップどの環境でも崩れないレスポンシブ構造と、Naver・Googleの検索で実際に露出するSEOの基本を全プロジェクトに標準適用します。公開後もコンテンツ更新や運用サポートを継続し、「作っただけのサイト」にしません。',
    s2k1:'企業/病院/機関', s2k2:'レスポンシブ', s2k3:'SEO',
    s3d:'初めて見る人でも製品・サービスの強みが一目で伝わるよう、ストーリー構成から設計したうえでカタログ・パンフレット・リーフレットに仕上げます。印刷用の高解像度CMYKファイルとオンライン配布用デジタルファイルを併せて納品するため、展示会・営業商談・ウェブサイトなどどこでもすぐに活用できます。海外バイヤー対応が必要な企業向けの多言語版制作にも対応します。',
    s3k1:'ブランディング', s3k2:'印刷物', s3k3:'パンフレット',
    s4d:'ISMS認証が初めての企業でも何から準備すべきか迷わないよう、現状のセキュリティレベルを診断するギャップ分析から始めます。不足部分を補うセキュリティポリシー・ガイドラインの策定、従業員教育、審査対応まで認証取得の全工程をともに進め、認証後の事後管理審査対応まで責任を持って支援します。規制対応のための書類ではなく、実際に機能するセキュリティ体制を作ることを目標としています。',
    s4k1:'ギャップ分析', s4k2:'認証支援', s4k3:'セキュリティポリシー',
    s5d:'Web・アプリ・サーバー全般を対象に、実際のハッカーが用いる侵入手法をそのまま再現してセキュリティ脆弱性を検証します。AI活用の自動分析で広範囲を高速にスキャンし、発見された箇所は専門家が直接侵入シナリオを設計して実践レベルで検証するハイブリッド方式を採用しています。診断で終わらせず、リスク別の優先順位と具体的な改善策を盛り込んだレポートを提供し、次に何から対応すべきかがすぐわかるようにします。',
    s5k1:'脆弱性診断', s5k2:'模擬ハッキング', s5k3:'セキュリティコンサルティング',
    cl_strip_tag:'取引先', cl_strip_title:'主要取引先',
    cl_link:'取引先をもっと見る →',
    cl_tag:'取引先', cl_title:'主要取引先',
    cl_desc:'さまざまな業界の企業と共に成長しています',
    cl_hosp:'医療/病院 多数', cl_neuro:'大韓神経科協会',
    cl_hosp_name:'医療機関 多数',
    cb_svc1:'セキュリティ脆弱性診断', cb_svc2:'映像制作', cb_svc3:'スマート農場 カタログ+サイト',
    cb_svc4:'多言語サイト · ERP', cb_svc5:'カタログ · IT MOU', cb_svc6:'ウェブサイト', cb_svc7:'ウェブサイト（準備中）',
    cb_svc8:'模擬ハッキング', cb_svc9:'ウェブサイト', cb_svc10:'フランチャイズサイト',
    cl_trust:'アンスロメタはGSリテール、LS産電をはじめ多数の企業・医療機関のウェブサイト制作を手がけ、信頼を積み重ねてきました。規模・業種を問わず最高のサービスを提供します。',
    ref_tag:'REFERENCES', ref_title:'プロジェクト実績', ref_desc:'アンスロメタが手がけた代表的なプロジェクトをご紹介します',
    rc1_cat:'セキュリティ脆弱性診断', rc1_t1:'流通大手企業', rc1_t2:'脆弱性診断', rc1_t3:'セキュリティコンサルティング',
    rc1_sub:'Security Assessment · 脆弱性診断プログラム',
    rc1_desc:'国内大手流通企業GSリテールのITインフラ・サービス全般を対象にセキュリティ脆弱性診断プログラムを実施しました。Web・アプリ・サーバー環境を対象に体系的な脆弱性診断を行い、発見されたセキュリティ課題に対する詳細レポートと優先度別の改善提案を提供しました。',
    rc1_l1:'Web・アプリ・サーバー全般の脆弱性診断', rc1_l2:'リスク評価と改善ガイドの提供',
    rc1_l3:'詳細な診断結果レポート作成', rc1_l4:'定期診断体制の構築支援',
    rc2_cat:'映像制作', rc2_t1:'企業PR動画', rc2_t2:'撮影・編集', rc2_t3:'モーショングラフィック',
    rc2_sub:'Video Production · 企業PRビデオ制作',
    rc2_desc:'ザ・ギバンの企業PR動画を企画から最終納品まで全工程担当しました。',
    rc2_l1:'企業PRビデオのストーリーボード企画', rc2_l2:'プロ機材による現場撮影',
    rc2_l3:'モーショングラフィック・字幕・BGM編集', rc2_l4:'YouTube・SNS・PPT 複数フォーマット納品',
    rc3_cat:'カタログ+サイト', rc3_t1:'製品カタログ', rc3_t2:'企業サイト', rc3_t3:'B2B',
    rc3_sub:'Catalog Design + Website · 製造・技術専門企業',
    rc3_desc:'ギバンテックの製品カタログとウェブサイトを同時に制作・納品しました。',
    rc3_l1:'製品ラインナップ全体カタログ制作', rc3_l2:'B2B営業特化デザイン',
    rc3_l3:'企業ウェブサイト設計・構築', rc3_l4:'デジタル・印刷兼用高解像度ファイル',
    rc4_cat:'多言語サイト+カタログ', rc4_t1:'多言語サイト', rc4_t2:'カタログ', rc4_t3:'ERP準備中',
    rc4_ongoing:'ERP導入進行中',
    rc4_sub:'多言語ウェブサイト+カタログ · ERP導入準備中',
    rc4_desc:'グローバル市場向けに3言語対応（韓英日）のウェブサイトと英語カタログを制作。現在はERP導入コンサルティングを進めています。',
    rc4_l1:'韓国語・英語・日本語 多言語サイト構築', rc4_l2:'海外バイヤー向け英語カタログ制作',
    rc4_l3:'グローバルSEO・海外検索露出強化', rc4_l4:'カスタムERP導入コンサルティング（進行中）',
    rc5_cat:'カタログ+IT MOU', rc5_t1:'ブランドカタログ', rc5_t2:'パンフレット', rc5_t3:'IT MOU',
    rc5_ongoing:'MOUパートナー',
    rc5_sub:'カタログデザイン · ITコンサルティングMOU · 戦略的ITパートナーシップ',
    rc5_desc:'バット＆バットのブランドカタログを制作し、その後ITコンサルティング分野でMOUを締結、長期的な戦略的パートナーシップを構築しました。',
    rc5_l1:'ブランドカタログ全面企画・制作', rc5_l2:'印刷CMYK+デジタルRGBデュアル納品',
    rc5_l3:'ITコンサルティングMOU締結', rc5_l4:'デジタル変革ロードマップ共同策定',
    rc6_cat:'医療機関サイト', rc6_t1:'病院・クリニック', rc6_t2:'予約連動', rc6_t3:'モバイル最適化',
    rc6_name:'医療機関 多数',
    rc6_sub:'Medical Website · 病院・医院・クリニックサイト',
    rc6_desc:'内科・皮膚科・歯科・漢方医院など多様な診療科の医療機関サイトを多数制作・納品した実績があります。',
    rc6_l1:'患者中心UX医療サイト構築', rc6_l2:'診療科・医師・施設紹介ページ',
    rc6_l3:'オンライン予約システム連動', rc6_l4:'医療法遵守・個人情報保護設計',
    rc7_cat:'医療団体サイト', rc7_t1:'医療専門団体', rc7_t2:'機関サイト', rc7_t3:'準備中',
    rc7_ongoing:'制作準備中',
    rc7_name:'大韓神経科協会',
    rc7_sub:'Medical Association Website · 全国医療専門団体の公式サイト',
    rc7_desc:'全国の神経科専門医を代表する大韓神経科協会の公式サイト構築を準備しています。',
    rc7_l1:'全国神経科専門医協会の公式サイト構築', rc7_l2:'会員管理・学術情報・学会日程統合',
    rc7_l3:'専門家・一般向けデュアルUX設計', rc7_l4:'アクセシビリティ+多言語対応予定',
    rc8_cat:'模擬ハッキング', rc8_t1:'電気・電力機器メーカー', rc8_t2:'模擬ハッキング', rc8_t3:'侵害シナリオ分析',
    rc8_sub:'Penetration Testing · 模擬ハッキングセキュリティ診断',
    rc8_desc:'電気・電力設備の専門企業LS産電を対象に、実際の攻撃手法を用いた模擬ハッキングを実施しました。外部侵入・内部権限昇格・主要システムへのアクセス可能性など実践的な侵害シナリオに基づきセキュリティ脆弱性を検証し、対応策を含む総合セキュリティ診断結果を提供しました。',
    rc8_l1:'実践的攻撃手法による模擬ハッキング実施', rc8_l2:'外部侵入・内部権限昇格シナリオの検証',
    rc8_l3:'主要システムへのアクセス可能性分析', rc8_l4:'対応策を含む総合セキュリティ診断レポート提供',
    rc9_cat:'ウェブサイト制作', rc9_t1:'高齢者福祉機関', rc9_t2:'機関サイト', rc9_t3:'アクセシブルデザイン',
    rc9_sub:'Institutional Website · 高齢者福祉センター公式サイト',
    rc9_desc:'高陽（ゴヤン）シニアクラブの公式サイトを企画・設計・構築しました。大きな文字・高コントラストカラーなどアクセシビリティを考慮したUIを適用し、高齢者とその家族の双方が利用しやすいよう、機関紹介・プログラム案内・お知らせなどを直感的に構成しました。',
    rc9_l1:'高齢者福祉機関特化のアクセシビリティUI/UX', rc9_l2:'プログラム・お知らせコンテンツの構成',
    rc9_l3:'モバイル最適化レスポンシブデザイン', rc9_l4:'地域住民の利便性向上',
    rc10_cat:'フランチャイズサイト', rc10_t1:'外食フランチャイズ', rc10_t2:'加盟店案内', rc10_t3:'ブランドサイト',
    rc10_sub:'Franchise Website · フランチャイズブランドサイト構築',
    rc10_desc:'外食フランチャイズブランド「バオビール」の公式サイトを企画・設計・構築しました。ブランドストーリー・メニュー紹介・店舗案内に加え、加盟お問い合わせ機能を搭載し新規加盟店の獲得を支援。ブランドトーン＆マナーを一貫して反映したビジュアルで顧客の信頼性を高めました。',
    rc10_l1:'ブランドストーリー・メニュー・店舗案内コンテンツ構成', rc10_l2:'加盟お問い合わせ機能による新規加盟店獲得支援',
    rc10_l3:'ブランドトーン反映のビジュアルデザイン', rc10_l4:'モバイル最適化レスポンシブデザイン',
    ind_h:'多様な業界をカバーする専門性',
    cta_title:'プロジェクトを始める準備はできましたか？',
    cta_desc:'お気軽にお問い合わせください。迅速かつ丁寧にご回答します。',
    cta_btn:'今すぐお問い合わせ',
    qa_tag:'FAQ', qa_title:'よくある質問', qa_desc:'ご不明な点をご確認ください',
    q1q:'ウェブサイト制作にはどのくらいかかりますか？',
    q1a:'一般的な企業サイトの場合、企画・デザイン・開発を含め約4〜8週間かかります。プロジェクトの規模や要件によって異なり、病院や大規模機関の場合は追加時間が必要になることがあります。初回ご相談の際に正確なスケジュールをご案内します。',
    q2q:'ERP構築の費用はどのくらいですか？',
    q2a:'ERP構築費用は企業規模・モジュール数・カスタマイズの範囲によって大きく異なります。さまざまな予算に合わせたソリューションをご提案します。正確なお見積もりは要件定義後にご案内しますので、まずはお気軽にお問い合わせください。',
    q3q:'ISMS認証の準備にはどのくらいかかりますか？',
    q3a:'ISMS認証取得までは企業の現状に応じて通常6ヶ月〜1年程度かかります。ギャップ分析、ポリシー策定、管理策実装、内部監査、審査対応などのプロセスを経ます。専門コンサルタントが全工程を密着サポートします。',
    q4q:'サイト構築後の保守契約は可能ですか？',
    q4a:'はい、可能です。サイト構築完了後に月額保守契約を締結いただけます。コンテンツ更新、セキュリティパッチ、障害対応、機能改善などを含むカスタマイズされた保守プランを提供しています。',
    q5q:'小規模スタートアップでも依頼できますか？',
    q5a:'もちろんです。アンスロメタはスタートアップから中堅企業まで規模を問わずサービスを提供しています。予算と要件に最適なソリューションをご提案し、どんなプロジェクトにも同じ品質と情熱で取り組みます。お気軽にご相談ください。',
    ct_tag:'お問い合わせ', ct_title:'お問い合わせ',
    ct_desc:'プロジェクトについてお話しください。迅速かつ丁寧にご回答します。',
    ct_sub:'今すぐご相談を始めましょう', ct_kbtn:'カカオトークでお問い合わせ',
    ct_el:'メール', ct_pl:'電話', ct_ll:'所在地', ct_loc:'韓国 京畿道坡州市',
    why_tag:'選ばれる理由', why_title:'なぜアンスロメタか？', why_desc:'お客様の成功が私たちの使命です',
    why1_t:'専門性', why1_d:'ERP・ウェブ・カタログ・ISMS・セキュリティ・AI、それぞれの分野を表面的に知っているだけの担当者ではなく、実際にプロジェクトを最後までやり遂げた専任スペシャリストが企画から構築、引き渡しまで責任を持って担当します。再委託構造ではないため、伝達ロスがありません。',
    why2_t:'実績と信頼', why2_d:'GSリテールのセキュリティ脆弱性診断、LS産電の模擬ハッキングのような大企業案件から、多数の病院・医院、高齢者福祉施設、フランチャイズブランドまで——業種や規模を問わず積み重ねてきた納品実績こそが信頼の根拠です。',
    why3_t:'迅速な着手', why3_d:'お問い合わせ後、長くお待たせしません。初回相談で要件を明確に把握し、スケジュールを迅速に確定します。スケジュールが遅れがちな開発プロジェクトだからこそ、納期厳守を最優先の原則としています。',
    why4_t:'長期パートナー', why4_d:'納品はご関係の終わりではなく始まりです。運用中のお問い合わせ・障害対応はもちろん、事業成長にともなって必要になる機能拡張やアップグレードまで一緒に取り組み、長期的なパートナーシップを続けます。',
    proc_tag:'プロセス', proc_title:'プロジェクトの進め方',
    proc1_n:'01', proc1_t:'無料相談', proc1_d:'ビジネス目標と要件を丁寧にヒアリングし、プロジェクトの方向性を定めます。',
    proc2_n:'02', proc2_t:'企画・設計', proc2_d:'最適なソリューションを設計し、詳細な提案書と見積書を作成します。',
    proc3_n:'03', proc3_t:'開発・構築', proc3_d:'専任チームが高品質な基準で開発・実装を行います。',
    proc4_n:'04', proc4_t:'納品・サポート', proc4_d:'高品質な納品と継続的なアフターサポート・アップグレードを提供します。',
    s1b1:'業務プロセス分析・再設計', s1b2:'モジュール別カスタマイズ', s1b3:'データ移行・システム連携', s1b4:'従業員研修・運用サポート',
    s1b5:'導入後の継続的な保守・機能拡張サポート',
    s2b1:'企業・病院・機関サイト専門', s2b2:'レスポンシブ・モバイル最適化', s2b3:'SEO最適化・パフォーマンスチューニング', s2b4:'CMS連携・コンテンツ管理',
    s2b5:'公開後のコンテンツ更新・運用サポート継続',
    s3b1:'ブランドアイデンティティの完全反映', s3b2:'カタログ・パンフレット・リーフレット', s3b3:'デジタル・印刷デュアル制作', s3b4:'多言語版制作対応',
    s3b5:'展示会・営業資料にすぐ使えるフォーマット提供',
    s4b1:'ギャップ分析・ロードマップ策定', s4b2:'セキュリティポリシー文書化', s4b3:'従業員セキュリティ教育', s4b4:'審査対応・認証後管理',
    s4b5:'認証後の事後管理審査対応まで支援',
    s5b1:'Web・アプリ・サーバー全般の脆弱性診断', s5b2:'実践的攻撃手法による模擬ハッキング実施', s5b3:'AI活用の脆弱性分析自動化', s5b4:'対応策を含む総合セキュリティレポート提供',
    s5b5:'定期再点検体制の構築支援',
    s6t:'ローカルLLM AIソリューション', s6p:'オンプレミスAI · 完全プライベート',
    s6d:'ChatGPTのような外部クラウドAIに社内文書や顧客データを送りたくない企業のために、LLMを社内サーバーに直接構築・運用する完全オンプレミスAI環境を構築します。社内マニュアル・契約書・DBと連携したRAG(検索拡張生成)システムで「自社の業務を理解するAI」を作り、必要に応じて業種特化のファインチューニングも行います。インターネットが途切れても、外部サービスのポリシーが変わっても揺るがない完全閉域網AIで、セキュリティと生産性を同時に確保します。',
    s6k1:'オンプレミスAI', s6k2:'データセキュリティ', s6k3:'カスタムFine-tuning',
    s6b1:'社内サーバーLLM構築・GPU最適化', s6b2:'事業ドメイン特化ファインチューニング',
    s6b3:'社内文書・DB連携RAGシステム構築', s6b4:'完全クローズド運用 — データ漏洩ゼロ',
    s6b5:'オンプレミスGPUサーバー構築コンサルティング込み',
    rc3_t1:'スマートファーム専門企業',
    ind_h:'多様な業界をカバーする専門性',
    q6q:'契約はどのように進みますか？',
    q6a:'要件定義後、見積書と契約書を作成します。支払いは一般的に着手金50%・中間金30%・残金20%ですが、規模に応じて協議可能です。契約書には成果物・スケジュール・検収基準が明確に記載されます。',
    q7q:'地方の企業でも依頼できますか？',
    q7a:'もちろんです。京畿道坡州を拠点としていますが、ビデオ会議とリモートツールで全国対応が可能です。対面と変わらない品質のサービスを提供し、必要に応じて訪問対応も協議できます。',
    q8q:'ポートフォリオや実績は確認できますか？',
    q8a:'カカオトークまたはメールでご連絡ください。守秘義務の範囲内で業種別ポートフォリオと実績をできる限り詳しくご案内します。',
    ind_title:'対応業種', ind1:'製造業', ind2:'医療・バイオ', ind3:'IT・ソフトウェア', ind4:'流通・物流', ind5:'公共・機関', ind6:'スタートアップ',
    ct_hrs_title:'営業時間', ct_hrs:'平日 09:00 – 18:00\n（土日・祝日は休業）',
    ct_resp_title:'返答時間', ct_resp:'お問い合わせ後\n24時間以内にご回答',
    ft_co:'アンスロメタ', ft_loc:'京畿道坡州市', ft_est:'設立 2022年4月', ft_r:'All rights reserved.',
    /* Own Services */
    own_tag:'OWN SERVICES', own_title:'アンスロメタが自社運営するサービス',
    own_desc:'外注制作にとどまらず、企画から開発・運営まで自社で責任を持つ自社サービスです',
    own_cta:'サイトへ →',
    os1_cat:'自社サービス・非公開運営', os1_t1:'ECオートメーション', os1_t2:'マルチマーケット連携', os1_t3:'無人運営',
    os1_name:'ドロップシッピング自動化プラットフォーム', os1_sub:'E-commerce Automation · AliExpress → 韓国国内マーケット完全自動化',
    os1_desc:'海外仕入れから国内販売まで全工程を自動化した自社運営ECプラットフォームです。商品ランキングアルゴリズムで仕入れ対象を選定し、スマートストア・11番街・Gマーケット/オークション・Coupangなど韓国主要マーケットプレイスに自動登録します。受注から発注、配送追跡、マージン計算、価格最適化、異常検知まで人手を介さず24時間運営されており、自社運営で得た実際のノウハウをそのままクライアントのEC自動化プロジェクトにも活かしています。',
    os1_l1:'AliExpress仕入れ→マージン計算→国内5マーケット自動登録', os1_l2:'受注・発注・配送追跡の無人自動化パイプライン',
    os1_l3:'価格最適化・異常検知・低調商品の自動入れ替え', os1_l4:'社内運営ツールのため、公開リンクの代わりにダッシュボードでご紹介',
    os2_cat:'自社サービス・コンテンツメディア', os2_t1:'ゲーム情報メディア', os2_t2:'自動収集パイプライン', os2_t3:'多言語SEO',
    os2_name:'cinoz.kr — Robloxゲーム情報', os2_sub:'Gaming Content Media · Roblox人気ゲームコード・情報サイト',
    os2_desc:'Roblox人気ゲームの最新コードと情報を韓国語・英語・日本語の3言語で提供するコンテンツメディアサービスです。毎時自動実行される収集パイプラインが新規ゲームの発掘、コード更新、サムネイル・ジャンル情報の補完までを自動処理し、広告収益化モデルも自社で設計・運営しています。',
    os2_l1:'韓・英・日の3言語対応、200以上のゲーム情報を提供', os2_l2:'毎時自動収集・更新されるゲーム・コードデータパイプライン',
    os2_l3:'SEO最適化および広告収益化（AdSense）の自社運営',
    os3_cat:'自社サービス・公共データプラットフォーム', os3_t1:'公共データ分析', os3_t2:'ローカル商圏発掘', os3_t3:'独自アルゴリズム',
    os3_name:'PinLocal — ローカルシークレット発掘プラットフォーム', os3_sub:'Public-Data Platform · 地域商圏データ分析サービス',
    os3_desc:'観光客にはあまり知られていないものの、実際には地元住民に愛されている商圏（"ローカルシークレット"）を発掘する公共データ基盤プラットフォームです。観光・商圏・許認可など複数の公共データを掛け合わせて分析する独自アルゴリズムで多様性・密集度・営業継続性・流入指数を算出して隠れた地域をスコア化し、地図ベースでおすすめコースまで自動生成します。',
    os3_l1:'複数の公共データを掛け合わせた独自発掘アルゴリズム', os3_l2:'地域別おすすめコースの自動生成と地図可視化',
    os3_l3:'全国規模へ拡張中の自動データ収集バッチシステム',
    os4_cat:'自社サービス・バーティカル情報プラットフォーム', os4_t1:'整備情報DB', os4_t2:'整備士ポートフォリオ', os4_t3:'コミュニティ',
    os4_name:'MechanicHub — 自動車整備情報プラットフォーム', os4_sub:'Vertical Information Platform · 整備士の実作業記録に基づくDB',
    os4_desc:'整備士が直接記録した実際の修理事例と400以上の故障コードデータベースに基づく自動車整備情報プラットフォームです。車種・世代・トリム別の整備規格、故障コードに紐づく実際の修理事例、整備士ポートフォリオと整備工場ダッシュボード、Q&Aコミュニティまで一つのサービスで統合提供します。',
    os4_l1:'実際の整備事例2,600件以上・故障コード400種以上のDB', os4_l2:'車種別定期点検規格＋故障コード連携の修理事例を提供',
    os4_l3:'整備士ポートフォリオ・整備工場ダッシュボード・Q&Aコミュニティを統合'
  }
};

let lang = localStorage.getItem('am-lang') || 'ko';

function setLang(l) {
  lang = l;
  localStorage.setItem('am-lang', l);
  document.documentElement.lang = {ko:'ko',en:'en',ja:'ja'}[l];
  document.body.className = 'lang-' + l;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    if (el.hasAttribute('data-notrans')) return;
    const v = T[l][el.getAttribute('data-i18n')];
    if (v != null) el.innerHTML = v;
  });
  ['ko','en','ja'].forEach(x => {
    const b = document.getElementById('b'+x);
    if (b) b.classList.toggle('active', x === l);
  });
}

/* Active nav */
function initNav() {
  const page = window.location.pathname.split('/').pop() || 'index.html';
  document.querySelectorAll('a[data-page]').forEach(a => {
    const p = a.getAttribute('data-page');
    a.classList.toggle('active-link', p === page || (page === '' && p === 'index.html'));
  });
}

/* Header scroll */
window.addEventListener('scroll', () => {
  const h = document.getElementById('hdr');
  if (h) h.classList.toggle('scrolled', scrollY > 20);
});

/* Mobile menu */
function toggleMenu() {
  document.getElementById('mnav').classList.toggle('open');
  document.getElementById('burg').classList.toggle('open');
}
function closeMenu() {
  document.getElementById('mnav').classList.remove('open');
  document.getElementById('burg').classList.remove('open');
}

/* FAQ */
function toggleFaq(btn) {
  const item = btn.parentElement;
  const wasOpen = item.classList.contains('open');
  document.querySelectorAll('.fi').forEach(i => i.classList.remove('open'));
  if (!wasOpen) item.classList.add('open');
}

/* Scroll reveal */
function initReveal() {
  const obs = new IntersectionObserver(entries => {
    entries.forEach(e => { if (e.isIntersecting) e.target.classList.add('vis'); });
  }, { threshold: 0.08, rootMargin: '0px 0px -40px 0px' });
  document.querySelectorAll('.reveal').forEach(el => obs.observe(el));
}

/* Init */
document.addEventListener('DOMContentLoaded', () => {
  setLang(lang);
  initNav();
  initReveal();
  // trigger scroll check for already-scrolled state on reload
  if (scrollY > 20) {
    const h = document.getElementById('hdr');
    if (h) h.classList.add('scrolled');
  }
});
